use reforger_language_server::parser::parse_source;
use reforger_language_server::syntax::{SyntaxElement, SyntaxKind, SyntaxNode};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/expression-fixtures.report.md";
const DEFAULT_STORAGE_RELATIVE_PATH: &str =
    "Code/User/globalStorage/undefined_publisher.reforger-sript-tools/game-data/scripts";

struct Fixture {
    path: String,
    source: String,
    status: &'static str,
}

fn main() -> Result<(), String> {
    let args = parse_args()?;
    let report = render_report(&args.scripts_path);

    if let Some(parent) = args.out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }
    fs::write(&args.out_path, report).map_err(|error| {
        format!(
            "Failed to write expression fixture report {}: {error}",
            args.out_path.display()
        )
    })?;

    println!(
        "Wrote expression fixture report: {}",
        args.out_path.display()
    );
    Ok(())
}

struct Args {
    scripts_path: PathBuf,
    out_path: PathBuf,
}

fn parse_args() -> Result<Args, String> {
    let mut scripts = None;
    let mut out = None;
    let mut args = env::args().skip(1);

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--scripts" => {
                let Some(value) = args.next() else {
                    return Err("--scripts requires a path".to_string());
                };
                scripts = Some(PathBuf::from(value));
            }
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example expression_report -- [--scripts <path>] [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(Args {
        scripts_path: scripts.unwrap_or_else(default_scripts_path),
        out_path: resolve_repo_path(out, DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn render_report(scripts_path: &Path) -> String {
    let mut report = String::new();
    report.push_str("# Expression Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example expression_report`.\n\n");
    report.push_str("This report reviews statement/expression syntax produced inside callable bodies. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures(scripts_path) {
        append_fixture_report(&mut report, &fixture);
    }

    report
}

fn fixtures(scripts_path: &Path) -> Vec<Fixture> {
    let mut fixtures = vec![
        Fixture {
            path: "tools/fixtures/parser/local_block_symbols.c".to_string(),
            source: include_str!("../../tools/fixtures/parser/local_block_symbols.c").to_string(),
            status: "game-data-derived committed fixture",
        },
        Fixture {
            path: "tools/fixtures/parser/modded_game_mode_members.c".to_string(),
            source: include_str!("../../tools/fixtures/parser/modded_game_mode_members.c")
                .to_string(),
            status: "game-data-derived committed fixture",
        },
    ];

    for relative in [
        "Game/GameMode/SCR_BaseGameMode.c",
        "Game/UI/Inventory/SCR_InventoryMenuUI.c",
        "Game/Editor/Containers/Attributes/SCR_DaytimeEditorAttribute.c",
        "GameLib/AnimateWidget.c",
        "WorkbenchGame/WorldEditor/SCR_FPSDiagnosticPlugin.c",
        "GameCode/World/TimeAndWeatherManagerEntity.c",
    ] {
        let path = scripts_path.join(relative);
        if let Ok(source) = fs::read_to_string(&path) {
            fixtures.push(Fixture {
                path: relative.to_string(),
                source,
                status: "game-data-derived local corpus sample",
            });
        }
    }

    fixtures
}

fn append_fixture_report(report: &mut String, fixture: &Fixture) {
    let parse = parse_source(&fixture.source);
    let mut counts = BTreeMap::new();
    count_interesting_kinds(&parse.root, &mut counts);

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str(&format!("Truth status: `{}`\n\n", fixture.status));
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!(
        "| Tokens preserved | {} |\n",
        parse.root.token_count()
    ));
    report.push_str(&format!("| Diagnostics | {} |\n", parse.diagnostics.len()));
    report.push_str(&format!(
        "| Max expression depth | {} |\n\n",
        max_expression_depth(&parse.root, 0)
    ));

    if !parse.diagnostics.is_empty() {
        report.push_str("### Diagnostics\n\n");
        for diagnostic in &parse.diagnostics {
            report.push_str(&format!(
                "- `{}` at {}..{}\n",
                diagnostic.message, diagnostic.span.start, diagnostic.span.end
            ));
        }
        report.push('\n');
    }

    report.push_str("### Statement / Expression Counts\n\n");
    report.push_str("| Syntax kind | Count |\n");
    report.push_str("| --- | ---: |\n");
    for (kind, count) in counts {
        report.push_str(&format!("| `{kind}` | {count} |\n"));
    }
    report.push('\n');

    report.push_str("### Body Syntax Outline\n\n");
    append_body_outline(report, &parse.root, 0, 180);
    report.push('\n');
}

fn count_interesting_kinds(node: &SyntaxNode, counts: &mut BTreeMap<String, usize>) {
    if is_statement_or_expression_kind(node.kind) {
        *counts.entry(format!("{:?}", node.kind)).or_default() += 1;
    }
    for child in &node.children {
        if let SyntaxElement::Node(child) = child {
            count_interesting_kinds(child, counts);
        }
    }
}

fn append_body_outline(
    report: &mut String,
    node: &SyntaxNode,
    depth: usize,
    remaining: usize,
) -> usize {
    if remaining == 0 {
        return 0;
    }

    let mut left = remaining;
    if is_statement_or_expression_kind(node.kind) {
        report.push_str(&format!(
            "{}- `{:?}` {}..{}\n",
            "  ".repeat(depth),
            node.kind,
            node.span.start,
            node.span.end
        ));
        left -= 1;
    }

    for child in &node.children {
        if left == 0 {
            break;
        }
        if let SyntaxElement::Node(child) = child {
            left = append_body_outline(report, child, depth + 1, left);
        }
    }
    left
}

fn max_expression_depth(node: &SyntaxNode, current: usize) -> usize {
    let next = if is_expression_kind(node.kind) {
        current + 1
    } else {
        current
    };
    node.children
        .iter()
        .filter_map(|child| match child {
            SyntaxElement::Node(child) => Some(max_expression_depth(child, next)),
            SyntaxElement::Token(_) => None,
        })
        .max()
        .unwrap_or(next)
}

fn is_statement_or_expression_kind(kind: SyntaxKind) -> bool {
    is_statement_kind(kind) || is_expression_kind(kind)
}

fn is_statement_kind(kind: SyntaxKind) -> bool {
    matches!(
        kind,
        SyntaxKind::IfStatement
            | SyntaxKind::ForStatement
            | SyntaxKind::ForeachStatement
            | SyntaxKind::WhileStatement
            | SyntaxKind::DoWhileStatement
            | SyntaxKind::SwitchStatement
            | SyntaxKind::CaseClause
            | SyntaxKind::DefaultClause
            | SyntaxKind::ReturnStatement
            | SyntaxKind::BreakStatement
            | SyntaxKind::ContinueStatement
            | SyntaxKind::DeleteStatement
            | SyntaxKind::ThreadStatement
            | SyntaxKind::EmptyStatement
            | SyntaxKind::LocalDeclStatement
            | SyntaxKind::ExpressionStatement
            | SyntaxKind::ForHeader
            | SyntaxKind::ForInitializer
            | SyntaxKind::ForCondition
            | SyntaxKind::ForIncrement
    )
}

fn is_expression_kind(kind: SyntaxKind) -> bool {
    matches!(
        kind,
        SyntaxKind::Expression
            | SyntaxKind::NameExpression
            | SyntaxKind::LiteralExpression
            | SyntaxKind::ParenthesizedExpression
            | SyntaxKind::UnaryExpression
            | SyntaxKind::BinaryExpression
            | SyntaxKind::AssignmentExpression
            | SyntaxKind::TernaryExpression
            | SyntaxKind::CallExpression
            | SyntaxKind::ArgumentList
            | SyntaxKind::NamedArgument
            | SyntaxKind::MemberAccessExpression
            | SyntaxKind::IndexExpression
            | SyntaxKind::CastExpression
            | SyntaxKind::PostfixExpression
            | SyntaxKind::NewExpression
            | SyntaxKind::InitializerExpression
    )
}

fn default_scripts_path() -> PathBuf {
    if let Some(app_data) = env::var_os("APPDATA") {
        PathBuf::from(app_data).join(DEFAULT_STORAGE_RELATIVE_PATH)
    } else {
        PathBuf::from(DEFAULT_STORAGE_RELATIVE_PATH)
    }
}

fn resolve_repo_path(path: Option<PathBuf>, default_relative_path: &str) -> PathBuf {
    match path {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(default_relative_path),
    }
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}
