use reforger_language_server::index::SymbolIndex;
use reforger_language_server::index_cache::{
    load_or_build_game_data_index, GameDataIndexCacheConfig, GameDataIndexCacheResult,
    IndexCacheStatus,
};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/index-cache-strings.report.md";
const DEFAULT_STORAGE_RELATIVE_PATH: &str =
    "Code/User/globalStorage/undefined_publisher.reforger-sript-tools";
const MAX_TOP_STRINGS: usize = 25;

struct Args {
    scripts_path: PathBuf,
    metadata_path: Option<PathBuf>,
    cache_path: PathBuf,
    out_path: PathBuf,
}

#[derive(Default)]
struct StringStats {
    groups: BTreeMap<&'static str, StringGroup>,
    all: StringGroup,
}

#[derive(Default)]
struct StringGroup {
    records: BTreeMap<String, StringRecord>,
}

#[derive(Default)]
struct StringRecord {
    occurrences: usize,
}

#[derive(Clone)]
struct StringRow {
    value: String,
    occurrences: usize,
    bytes: usize,
    duplicate_bytes: usize,
}

fn main() -> Result<(), String> {
    let args = parse_args()?;
    let report = render_report(&args)?;

    if let Some(parent) = args.out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&args.out_path, report).map_err(|error| {
        format!(
            "Failed to write index cache string duplication report {}: {error}",
            args.out_path.display()
        )
    })?;

    println!(
        "Wrote index cache string duplication report: {}",
        args.out_path.display()
    );
    Ok(())
}

fn parse_args() -> Result<Args, String> {
    let mut args = env::args().skip(1);
    let mut scripts: Option<PathBuf> = None;
    let mut metadata: Option<Option<PathBuf>> = None;
    let mut cache: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--scripts" => {
                let Some(value) = args.next() else {
                    return Err("--scripts requires a path".to_string());
                };
                scripts = Some(PathBuf::from(value));
            }
            "--metadata" => {
                let Some(value) = args.next() else {
                    return Err("--metadata requires a path or 'none'".to_string());
                };
                metadata = Some((value != "none").then(|| PathBuf::from(value)));
            }
            "--cache" => {
                let Some(value) = args.next() else {
                    return Err("--cache requires a path".to_string());
                };
                cache = Some(PathBuf::from(value));
            }
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!(
                    "Usage: cargo run --manifest-path server/Cargo.toml --example index_cache_strings_report -- [--scripts <path>] [--metadata <path|none>] [--cache <path>] [--out <path>]"
                );
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    let scripts_path = scripts.unwrap_or_else(default_scripts_path);
    let metadata_path = metadata.unwrap_or_else(|| default_metadata_path(&scripts_path));

    Ok(Args {
        scripts_path,
        metadata_path,
        cache_path: cache.unwrap_or_else(default_cache_path),
        out_path: resolve_repo_path(out, DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn render_report(args: &Args) -> Result<String, String> {
    let cache = load_or_build_game_data_index(&GameDataIndexCacheConfig {
        scripts_root: args.scripts_path.clone(),
        cache_path: args.cache_path.clone(),
        metadata_path: args.metadata_path.clone(),
    })?;
    let stats = collect_string_stats(&cache.index);

    let mut report = String::new();
    report.push_str("# Index Cache String Duplication Report\n\n");
    report.push_str(
        "> Dev-only report generated by `node tools/index-cache-strings-report.mjs`.\n\n",
    );
    report.push_str("This report measures repeated copied string values in the current runtime game-data cache. It is planning evidence for possible string interning or path-table cache work; it does not change cache format or runtime behavior.\n\n");
    append_inputs(&mut report, args);
    append_cache_status(&mut report, &cache);
    append_summary(&mut report, &stats);
    append_path_review(&mut report, &cache.index, &stats);
    append_group_summary(&mut report, &stats);
    append_top_duplicates(&mut report, &stats);
    append_recommendation(&mut report, &cache, &stats);
    Ok(report)
}

fn append_inputs(report: &mut String, args: &Args) {
    report.push_str("## Inputs\n\n");
    report.push_str("| Input | Path |\n");
    report.push_str("| --- | --- |\n");
    report.push_str(&format!(
        "| Game data scripts | `{}` |\n",
        args.scripts_path.display()
    ));
    report.push_str(&format!(
        "| Metadata | `{}` |\n",
        args.metadata_path
            .as_ref()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|| "none".to_string())
    ));
    report.push_str(&format!("| Cache | `{}` |\n", args.cache_path.display()));
    report.push_str(&format!(
        "| Scan timestamp unix seconds | `{}` |\n\n",
        timestamp()
    ));
}

fn append_cache_status(report: &mut String, cache: &GameDataIndexCacheResult) {
    report.push_str("## Cache Status\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!(
        "| Status | `{}` |\n",
        cache_status_label(&cache.cache_status)
    ));
    report.push_str(&format!(
        "| Cache file bytes | {} |\n",
        cache.cache_file_bytes.unwrap_or(0)
    ));
    report.push_str(&format!(
        "| Cache file MiB | {:.2} |\n",
        cache.cache_file_bytes.unwrap_or(0) as f64 / (1024.0 * 1024.0)
    ));
    report.push_str(&format!("| Files | {} |\n", cache.index.files().len()));
    report.push_str(&format!(
        "| Symbols | {} |\n\n",
        cache.index.symbols().len()
    ));
}

fn append_summary(report: &mut String, stats: &StringStats) {
    let total = group_totals(&stats.all);
    report.push_str("## String Duplication Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| String occurrences | {} |\n", total.occurrences));
    report.push_str(&format!("| Unique strings | {} |\n", total.unique_strings));
    report.push_str(&format!(
        "| Occurrence bytes | {} |\n",
        total.occurrence_bytes
    ));
    report.push_str(&format!("| Unique bytes | {} |\n", total.unique_bytes));
    report.push_str(&format!(
        "| Duplicate string bytes | {} |\n",
        total.duplicate_bytes
    ));
    report.push_str(&format!(
        "| Duplicate share of occurrence bytes | {} |\n\n",
        percent(total.duplicate_bytes, total.occurrence_bytes)
    ));
}

fn append_path_review(report: &mut String, index: &SymbolIndex, stats: &StringStats) {
    let absolute = stats
        .groups
        .get("file.absolute_path")
        .map(group_totals)
        .unwrap_or_default();
    let root = stats
        .groups
        .get("file.root_path")
        .map(group_totals)
        .unwrap_or_default();
    let relative = stats
        .groups
        .get("file.relative_path")
        .map(group_totals)
        .unwrap_or_default();
    let absolute_minus_relative = absolute
        .occurrence_bytes
        .saturating_sub(relative.occurrence_bytes);

    report.push_str("## Path String Review\n\n");
    report.push_str("The v9 binary cache stores repeated strings through an interned string table. The decoded index still carries absolute path, root path, and relative path per file for debug and navigation output, so this section remains useful for judging future path-table or decoded-memory work.\n\n");
    report.push_str("| Path string group | Occurrences | Unique strings | Occurrence bytes | Duplicate bytes |\n");
    report.push_str("| --- | ---: | ---: | ---: | ---: |\n");
    report.push_str(&format!(
        "| Absolute paths | {} | {} | {} | {} |\n",
        absolute.occurrences,
        absolute.unique_strings,
        absolute.occurrence_bytes,
        absolute.duplicate_bytes
    ));
    report.push_str(&format!(
        "| Root paths | {} | {} | {} | {} |\n",
        root.occurrences, root.unique_strings, root.occurrence_bytes, root.duplicate_bytes
    ));
    report.push_str(&format!(
        "| Relative paths | {} | {} | {} | {} |\n",
        relative.occurrences,
        relative.unique_strings,
        relative.occurrence_bytes,
        relative.duplicate_bytes
    ));
    report.push_str(&format!(
        "| Absolute path bytes beyond relative path bytes | {} |  | {} |  |\n\n",
        index.files().len(),
        absolute_minus_relative
    ));
}

fn append_group_summary(report: &mut String, stats: &StringStats) {
    let mut rows = stats
        .groups
        .iter()
        .map(|(group, values)| (*group, group_totals(values)))
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| {
        right
            .1
            .duplicate_bytes
            .cmp(&left.1.duplicate_bytes)
            .then_with(|| left.0.cmp(right.0))
    });

    report.push_str("## Duplication By String Group\n\n");
    report.push_str("| Group | Occurrences | Unique | Occurrence bytes | Unique bytes | Duplicate bytes | Duplicate % |\n");
    report.push_str("| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n");
    for (group, totals) in rows {
        if totals.occurrences == 0 {
            continue;
        }
        report.push_str(&format!(
            "| `{group}` | {} | {} | {} | {} | {} | {} |\n",
            totals.occurrences,
            totals.unique_strings,
            totals.occurrence_bytes,
            totals.unique_bytes,
            totals.duplicate_bytes,
            percent(totals.duplicate_bytes, totals.occurrence_bytes)
        ));
    }
    report.push('\n');
}

fn append_top_duplicates(report: &mut String, stats: &StringStats) {
    report.push_str("## Top Duplicate Strings By Group\n\n");
    for (group, values) in &stats.groups {
        let mut rows = duplicate_rows(values);
        rows.truncate(MAX_TOP_STRINGS);
        if rows.is_empty() {
            continue;
        }

        report.push_str(&format!("### `{group}`\n\n"));
        report.push_str("| String | Occurrences | Bytes | Duplicate bytes |\n");
        report.push_str("| --- | ---: | ---: | ---: |\n");
        for row in rows {
            report.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                markdown_inline(&row.value),
                row.occurrences,
                row.bytes,
                row.duplicate_bytes
            ));
        }
        report.push('\n');
    }
}

fn append_recommendation(
    report: &mut String,
    cache: &GameDataIndexCacheResult,
    stats: &StringStats,
) {
    let total = group_totals(&stats.all);
    let path_duplicate_bytes = ["file.absolute_path", "file.root_path", "file.relative_path"]
        .iter()
        .filter_map(|group| stats.groups.get(group))
        .map(|group| group_totals(group).duplicate_bytes)
        .sum::<usize>();
    let cache_bytes = cache.cache_file_bytes.unwrap_or(0) as usize;

    report.push_str("## Recommendation\n\n");
    if total.duplicate_bytes > cache_bytes / 4 {
        report.push_str("String interning or table-based cache storage is worth a focused design slice. Duplicate string value bytes are a large share of the cache, and this can be improved without dropping editor-visible facts.\n\n");
    } else {
        report.push_str("String duplication exists, but it is not yet large enough by itself to justify a cache-format redesign. Prefer editor feature work unless real runtime memory/startup measurements show pressure.\n\n");
    }
    report.push_str(&format!(
        "- Duplicate string bytes: {} of cache bytes {} ({})\n",
        total.duplicate_bytes,
        cache_bytes,
        percent(total.duplicate_bytes, cache_bytes)
    ));
    report.push_str(&format!(
        "- Path duplicate bytes: {} ({}) of duplicate string bytes\n",
        path_duplicate_bytes,
        percent(path_duplicate_bytes, total.duplicate_bytes)
    ));
    report.push_str("- A future no-feature-loss optimization should start with a string table and path table, not visibility pruning.\n");
    report.push_str("- Keep source files and parser/model/index output as truth; any interned cache remains disposable.\n\n");
}

fn collect_string_stats(index: &SymbolIndex) -> StringStats {
    let mut stats = StringStats::default();

    for file in index.files() {
        add_path(
            &mut stats,
            "file.absolute_path",
            file.metadata.absolute_path.as_deref(),
        );
        add_path(
            &mut stats,
            "file.root_path",
            file.metadata.root_path.as_deref(),
        );
        add_path(
            &mut stats,
            "file.relative_path",
            file.metadata.relative_path.as_deref(),
        );
    }

    for symbol in index.symbols() {
        add_option(&mut stats, "symbol.name", symbol.name.as_deref());
        add_option(
            &mut stats,
            "detail.type_text",
            symbol.detail.type_text.as_deref(),
        );
        add_option(
            &mut stats,
            "detail.return_type_text",
            symbol.detail.return_type_text.as_deref(),
        );
        add_option(
            &mut stats,
            "detail.base_type",
            symbol.detail.base_type.as_deref(),
        );
        add_option(
            &mut stats,
            "detail.default_text",
            symbol.detail.default_text.as_deref(),
        );
        add_option(
            &mut stats,
            "detail.enum_value_text",
            symbol.detail.enum_value_text.as_deref(),
        );
        for modifier in &symbol.modifiers {
            add_string(&mut stats, "modifier.text", modifier);
        }
        for attribute in &symbol.attributes {
            add_option(&mut stats, "attribute.name", attribute.name.as_deref());
            add_string(&mut stats, "attribute.raw_text", &attribute.text);
        }
        for doc in &symbol.doc_comments {
            add_string(&mut stats, "doc.raw_text", &doc.text);
        }
        for branch in &symbol.conditional_context {
            add_option(
                &mut stats,
                "conditional.condition",
                branch.condition.as_deref(),
            );
        }
    }

    stats
}

fn add_path(stats: &mut StringStats, group: &'static str, value: Option<&Path>) {
    if let Some(value) = value {
        add_string(stats, group, &value.to_string_lossy());
    }
}

fn add_option(stats: &mut StringStats, group: &'static str, value: Option<&str>) {
    if let Some(value) = value {
        add_string(stats, group, value);
    }
}

fn add_string(stats: &mut StringStats, group: &'static str, value: &str) {
    if value.is_empty() {
        return;
    }
    stats
        .groups
        .entry(group)
        .or_default()
        .records
        .entry(value.to_string())
        .or_default()
        .occurrences += 1;
    stats
        .all
        .records
        .entry(value.to_string())
        .or_default()
        .occurrences += 1;
}

#[derive(Default)]
struct GroupTotals {
    occurrences: usize,
    unique_strings: usize,
    occurrence_bytes: usize,
    unique_bytes: usize,
    duplicate_bytes: usize,
}

fn group_totals(group: &StringGroup) -> GroupTotals {
    let mut totals = GroupTotals::default();
    for (value, record) in &group.records {
        let bytes = value.len() * record.occurrences;
        totals.occurrences += record.occurrences;
        totals.unique_strings += 1;
        totals.occurrence_bytes += bytes;
        totals.unique_bytes += value.len();
        totals.duplicate_bytes += bytes.saturating_sub(value.len());
    }
    totals
}

fn duplicate_rows(group: &StringGroup) -> Vec<StringRow> {
    let mut rows = group
        .records
        .iter()
        .filter(|(_, record)| record.occurrences > 1)
        .map(|(value, record)| {
            let bytes = value.len() * record.occurrences;
            StringRow {
                value: value.clone(),
                occurrences: record.occurrences,
                bytes,
                duplicate_bytes: bytes.saturating_sub(value.len()),
            }
        })
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| {
        right
            .duplicate_bytes
            .cmp(&left.duplicate_bytes)
            .then_with(|| right.occurrences.cmp(&left.occurrences))
            .then_with(|| left.value.cmp(&right.value))
    });
    rows
}

fn cache_status_label(status: &IndexCacheStatus) -> String {
    match status {
        IndexCacheStatus::Loaded => "loaded".to_string(),
        IndexCacheStatus::Rebuilt { reason } => format!("rebuilt ({reason})"),
    }
}

fn markdown_inline(value: &str) -> String {
    let mut value = value.replace('\\', "\\\\").replace('`', "\\`");
    value = value.replace('\n', "\\n").replace('\r', "\\r");
    if value.len() > 160 {
        value.truncate(157);
        value.push_str("...");
    }
    value
}

fn percent(part: usize, total: usize) -> String {
    if total == 0 {
        return "0.0%".to_string();
    }
    format!("{:.1}%", part as f64 * 100.0 / total as f64)
}

fn timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

fn resolve_repo_path(path: Option<PathBuf>, default_relative: &str) -> PathBuf {
    path.unwrap_or_else(|| repo_root().join(default_relative))
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn default_scripts_path() -> PathBuf {
    default_storage_root().join("game-data/scripts")
}

fn default_metadata_path(scripts_path: &Path) -> Option<PathBuf> {
    let metadata = scripts_path
        .parent()
        .map(|game_data| game_data.join("metadata.json"))?;
    metadata.is_file().then_some(metadata)
}

fn default_cache_path() -> PathBuf {
    default_storage_root().join("index-cache/game-data-symbol-index.v9.bin")
}

fn default_storage_root() -> PathBuf {
    if let Ok(appdata) = env::var("APPDATA") {
        return PathBuf::from(appdata).join(DEFAULT_STORAGE_RELATIVE_PATH);
    }

    if let Ok(home) = env::var("USERPROFILE") {
        return PathBuf::from(home)
            .join("AppData/Roaming")
            .join(DEFAULT_STORAGE_RELATIVE_PATH);
    }

    PathBuf::from(DEFAULT_STORAGE_RELATIVE_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;
    use reforger_language_server::index::SymbolIndex;
    use reforger_language_server::model::{
        SourceCategory, SourceFileMetadata, SourceKind, SOURCE_PRIORITY_GAME_DATA,
    };
    use reforger_language_server::parser::parse_source;
    use reforger_language_server::semantic_file::SemanticFile;

    #[test]
    fn counts_duplicate_strings_by_group() {
        let mut stats = StringStats::default();
        add_string(&mut stats, "modifier.text", "protected");
        add_string(&mut stats, "modifier.text", "protected");
        add_string(&mut stats, "modifier.text", "static");

        let modifier = group_totals(stats.groups.get("modifier.text").unwrap());
        assert_eq!(modifier.occurrences, 3);
        assert_eq!(modifier.unique_strings, 2);
        assert_eq!(modifier.duplicate_bytes, "protected".len());

        let all = group_totals(&stats.all);
        assert_eq!(all.duplicate_bytes, "protected".len());
    }

    #[test]
    fn collects_cache_string_sources_from_index() {
        let source = r#"//! Docs
[Attribute("1")]
class Example : BaseExample
{
	protected ref array<int> m_Values;
	void Run(string name = "ok");
}
"#;
        let index = index_for_source(source);
        let stats = collect_string_stats(&index);

        assert!(group_totals(stats.groups.get("file.root_path").unwrap()).occurrences > 0);
        assert!(stats
            .groups
            .get("symbol.name")
            .unwrap()
            .records
            .contains_key("Example"));
        assert!(stats
            .groups
            .get("detail.type_text")
            .unwrap()
            .records
            .contains_key("ref array<int>"));
        assert!(stats
            .groups
            .get("modifier.text")
            .unwrap()
            .records
            .contains_key("protected"));
        assert!(stats
            .groups
            .get("attribute.raw_text")
            .unwrap()
            .records
            .contains_key("[Attribute(\"1\")]"));
        assert!(stats
            .groups
            .get("doc.raw_text")
            .unwrap()
            .records
            .contains_key("//! Docs"));
    }

    fn index_for_source(source: &str) -> SymbolIndex {
        let parse = parse_source(source);
        let metadata = SourceFileMetadata {
            kind: SourceKind::GameData,
            category: SourceCategory::Game,
            absolute_path: Some(PathBuf::from("C:/root/Game/Example.c")),
            virtual_source: None,
            root_path: Some(PathBuf::from("C:/root")),
            relative_path: Some(PathBuf::from("Game/Example.c")),
            priority: SOURCE_PRIORITY_GAME_DATA,
        };
        let semantic_file = SemanticFile::build(source, &parse);
        SymbolIndex::from_semantic_files([(&semantic_file, metadata)])
    }
}
