use reforger_language_server::lexer::TextSpan;
use reforger_language_server::model::{
    source_category_for_path, SourceFileMetadata, SourceKind, SOURCE_PRIORITY_FIXTURE,
};
use reforger_language_server::parser::parse_source;
use reforger_language_server::semantic_file::{
    SemanticDeclaration, SemanticDeclarationId, SemanticDeclarationKind, SemanticFile, SemanticText,
};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/symbol-fixtures.report.md";

struct Fixture {
    path: &'static str,
    source: &'static str,
}

fn main() -> Result<(), String> {
    let out_path = output_path()?;
    let report = render_report();

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&out_path, report).map_err(|error| {
        format!(
            "Failed to write symbol fixture report {}: {error}",
            out_path.display()
        )
    })?;

    println!("Wrote symbol fixture report: {}", out_path.display());
    Ok(())
}

fn output_path() -> Result<PathBuf, String> {
    let mut args = env::args().skip(1);
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example symbol_report -- [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn fixtures() -> [Fixture; 11] {
    [
        Fixture {
            path: "tools/fixtures/parser/core_types_declarations.c",
            source: include_str!("../../tools/fixtures/parser/core_types_declarations.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/attributes_rpc_workbench.c",
            source: include_str!("../../tools/fixtures/parser/attributes_rpc_workbench.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/modded_game_mode_members.c",
            source: include_str!("../../tools/fixtures/parser/modded_game_mode_members.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/preprocessor_directives.c",
            source: include_str!("../../tools/fixtures/parser/preprocessor_directives.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_network_component.c",
            source: include_str!("../../tools/fixtures/parser/game_building_network_component.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_provider_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_building_provider_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editable_group_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_editable_group_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editor_preview_params.c",
            source: include_str!("../../tools/fixtures/parser/game_editor_preview_params.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c",
            source: include_str!(
                "../../tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c"
            ),
        },
        Fixture {
            path: "tools/fixtures/parser/game_optional_semicolon_shapes.c",
            source: include_str!("../../tools/fixtures/parser/game_optional_semicolon_shapes.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_field_initializer_call_shapes.c",
            source: include_str!(
                "../../tools/fixtures/parser/game_field_initializer_call_shapes.c"
            ),
        },
    ]
}

fn render_report() -> String {
    let mut report = String::new();
    report.push_str("# Symbol Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example symbol_report`.\n\n");
    report.push_str("This report renders file-local symbol trees from committed parser fixtures. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures() {
        append_fixture(&mut report, fixture);
    }

    report
}

fn append_fixture(report: &mut String, fixture: Fixture) {
    let parse = parse_source(fixture.source);
    let metadata = fixture_metadata(fixture.path);
    let semantic_file = SemanticFile::build(fixture.source, &parse);

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str("### Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Source kind | `{}` |\n", metadata.kind.as_str()));
    report.push_str(&format!(
        "| Relative path | `{}` |\n",
        display_optional_path(&metadata.relative_path)
    ));
    report.push_str(&format!("| Source priority | {} |\n", metadata.priority));
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!(
        "| Parse diagnostics | {} |\n",
        parse.diagnostics.len()
    ));
    report.push_str(&format!(
        "| Symbols | {} |\n",
        semantic_file.declarations().len()
    ));
    report.push_str(&format!(
        "| Non-declaration callable fragments | {} |\n\n",
        semantic_file.non_declaration_callable_fragments()
    ));

    report.push_str("### Symbol Tree\n\n");
    for record in semantic_file
        .declarations()
        .iter()
        .filter(|record| record.parent.is_none())
    {
        append_symbol_tree(report, fixture.source, &semantic_file, record, 0);
    }
    report.push('\n');
}

fn fixture_metadata(path: &str) -> SourceFileMetadata {
    let root = repo_root();
    let relative_path = PathBuf::from(path);
    SourceFileMetadata {
        kind: SourceKind::Fixture,
        category: source_category_for_path(SourceKind::Fixture, Some(&relative_path)),
        absolute_path: Some(root.join(path)),
        virtual_source: None,
        root_path: Some(root),
        relative_path: Some(relative_path),
        priority: SOURCE_PRIORITY_FIXTURE,
    }
}

fn append_symbol_tree(
    report: &mut String,
    source: &str,
    semantic_file: &SemanticFile,
    record: &SemanticDeclaration,
    depth: usize,
) {
    let indent = "  ".repeat(depth);
    report.push_str(&format!(
        "{indent}- {} `{}` id {} parent `{}` decl {} selection {}{} attrs {} modifiers `{}` docs {} preview `{}`\n",
        kind_name(record.kind),
        display_name(record),
        record.id.0,
        display_parent(record.parent),
        display_location(source, record.span),
        display_location(source, record.selection_span),
        display_detail(record),
        display_attributes(&record.attributes),
        display_texts(&record.modifiers),
        record.doc_comments.len(),
        doc_preview(record),
    ));

    for child in semantic_file
        .declarations()
        .iter()
        .filter(|child| child.parent == Some(record.id))
    {
        append_symbol_tree(report, source, semantic_file, child, depth + 1);
    }
}

fn kind_name(kind: SemanticDeclarationKind) -> &'static str {
    match kind {
        SemanticDeclarationKind::Class => "Class",
        SemanticDeclarationKind::TypeParameter => "TypeParameter",
        SemanticDeclarationKind::Enum => "Enum",
        SemanticDeclarationKind::EnumMember => "EnumMember",
        SemanticDeclarationKind::Typedef => "Typedef",
        SemanticDeclarationKind::Function => "Function",
        SemanticDeclarationKind::GlobalField => "GlobalField",
        SemanticDeclarationKind::Field => "Field",
        SemanticDeclarationKind::Method => "Method",
        SemanticDeclarationKind::Constructor => "Constructor",
        SemanticDeclarationKind::Destructor => "Destructor",
        SemanticDeclarationKind::Parameter => "Parameter",
        SemanticDeclarationKind::LocalVariable => "LocalVariable",
        SemanticDeclarationKind::PreprocessorMacro => "PreprocessorMacro",
    }
}

fn display_name(record: &SemanticDeclaration) -> String {
    record
        .name
        .as_ref()
        .map(|name| escape_inline(&name.text))
        .unwrap_or_else(|| "<unknown>".to_string())
}

fn display_parent(parent: Option<SemanticDeclarationId>) -> String {
    parent
        .map(|id| id.0.to_string())
        .unwrap_or_else(|| "none".to_string())
}

fn display_detail(record: &SemanticDeclaration) -> String {
    let mut values = Vec::new();
    push_detail(&mut values, "type", record.detail.type_text.as_ref());
    push_detail(&mut values, "return", record.detail.return_type.as_ref());
    push_detail(&mut values, "base", record.detail.base_type.as_ref());
    push_detail(&mut values, "default", record.detail.default_value.as_ref());
    push_detail(&mut values, "enum_value", record.detail.enum_value.as_ref());

    if values.is_empty() {
        String::new()
    } else {
        format!(" {}", values.join(" "))
    }
}

fn push_detail(values: &mut Vec<String>, label: &str, text: Option<&SemanticText>) {
    if let Some(text) = text {
        values.push(format!("{label} `{}`", escape_inline(&text.text)));
    }
}

fn display_texts(values: &[SemanticText]) -> String {
    let text = values
        .iter()
        .map(|value| escape_inline(&value.text))
        .collect::<Vec<_>>();
    if text.is_empty() {
        "<none>".to_string()
    } else {
        text.join(" ")
    }
}

fn display_attributes(attributes: &[SemanticText]) -> String {
    let names = attributes
        .iter()
        .map(|attribute| escape_inline(attribute_name(&attribute.text)))
        .collect::<Vec<_>>();
    if names.is_empty() {
        "<none>".to_string()
    } else {
        format!("[{}]", names.join(", "))
    }
}

fn attribute_name(text: &str) -> &str {
    text.trim()
        .trim_start_matches('[')
        .split(['(', ']'])
        .next()
        .unwrap_or(text)
        .trim()
}

fn doc_preview(record: &SemanticDeclaration) -> String {
    record
        .doc_comments
        .first()
        .map(|comment| doc_text_preview(&comment.text))
        .unwrap_or_else(|| "<none>".to_string())
}

fn doc_text_preview(value: &str) -> String {
    let cleaned = value
        .lines()
        .map(clean_doc_line)
        .find(|line| !line.is_empty())
        .unwrap_or_else(|| value.trim().to_string());
    escape_inline(&cleaned)
}

fn clean_doc_line(line: &str) -> String {
    line.trim()
        .trim_start_matches("//!")
        .trim_start_matches("///<")
        .trim_start_matches("//")
        .trim_start_matches("/*!")
        .trim_start_matches("/**")
        .trim_start_matches("/*")
        .trim_start_matches('*')
        .trim_end_matches("*/")
        .trim()
        .to_string()
}

fn display_location(source: &str, span: TextSpan) -> String {
    let (line, column) = line_column(source, span.start);
    format!("{}:{} span {}..{}", line, column, span.start, span.end)
}

fn line_column(source: &str, offset: usize) -> (usize, usize) {
    let mut line = 1usize;
    let mut column = 1usize;

    for (index, value) in source.char_indices() {
        if index >= offset {
            break;
        }

        if value == '\n' {
            line += 1;
            column = 1;
        } else {
            column += 1;
        }
    }

    (line, column)
}

fn escape_inline(value: &str) -> String {
    value.replace('`', "\\`").replace('\n', "\\n")
}

fn display_optional_path(path: &Option<PathBuf>) -> String {
    path.as_ref()
        .map(|path| path.display().to_string())
        .unwrap_or_else(|| "<none>".to_string())
}
