use reforger_language_server::ast::AstSourceFile;
use reforger_language_server::lexer::TextSpan;
use reforger_language_server::model::{
    source_category_for_path, SourceFileMetadata, SourceKind, SymbolCatalog, SymbolId, SymbolKind,
    SymbolRecord, SOURCE_PRIORITY_FIXTURE,
};
use reforger_language_server::parser::parse_source;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/symbol-fixtures.report.md";

struct Fixture {
    path: &'static str,
    source: &'static str,
}

fn main() -> Result<(), String> {
    let out_path = output_path()?;
    let report = render_report();

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&out_path, report).map_err(|error| {
        format!(
            "Failed to write symbol fixture report {}: {error}",
            out_path.display()
        )
    })?;

    println!("Wrote symbol fixture report: {}", out_path.display());
    Ok(())
}

fn output_path() -> Result<PathBuf, String> {
    let mut args = env::args().skip(1);
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example symbol_report -- [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn fixtures() -> [Fixture; 11] {
    [
        Fixture {
            path: "tools/fixtures/parser/core_types_declarations.c",
            source: include_str!("../../tools/fixtures/parser/core_types_declarations.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/attributes_rpc_workbench.c",
            source: include_str!("../../tools/fixtures/parser/attributes_rpc_workbench.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/modded_game_mode_members.c",
            source: include_str!("../../tools/fixtures/parser/modded_game_mode_members.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/preprocessor_directives.c",
            source: include_str!("../../tools/fixtures/parser/preprocessor_directives.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_network_component.c",
            source: include_str!("../../tools/fixtures/parser/game_building_network_component.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_provider_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_building_provider_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editable_group_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_editable_group_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editor_preview_params.c",
            source: include_str!("../../tools/fixtures/parser/game_editor_preview_params.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c",
            source: include_str!(
                "../../tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c"
            ),
        },
        Fixture {
            path: "tools/fixtures/parser/game_optional_semicolon_shapes.c",
            source: include_str!("../../tools/fixtures/parser/game_optional_semicolon_shapes.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_field_initializer_call_shapes.c",
            source: include_str!(
                "../../tools/fixtures/parser/game_field_initializer_call_shapes.c"
            ),
        },
    ]
}

fn render_report() -> String {
    let mut report = String::new();
    report.push_str("# Symbol Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example symbol_report`.\n\n");
    report.push_str("This report renders file-local symbol trees from committed parser fixtures. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures() {
        append_fixture(&mut report, fixture);
    }

    report
}

fn append_fixture(report: &mut String, fixture: Fixture) {
    let parse = parse_source(fixture.source);
    let ast = AstSourceFile::new(fixture.source, &parse);
    let metadata = fixture_metadata(fixture.path);
    let catalog = SymbolCatalog::from_ast_with_metadata(fixture.source, &ast, metadata);

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str("### Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!(
        "| Source kind | `{}` |\n",
        catalog.metadata().kind.as_str()
    ));
    report.push_str(&format!(
        "| Relative path | `{}` |\n",
        display_optional_path(&catalog.metadata().relative_path)
    ));
    report.push_str(&format!(
        "| Source priority | {} |\n",
        catalog.metadata().priority
    ));
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!(
        "| Parse diagnostics | {} |\n",
        parse.diagnostics.len()
    ));
    report.push_str(&format!("| Symbols | {} |\n", catalog.records().len()));
    report.push_str(&format!(
        "| Non-declaration callable fragments | {} |\n\n",
        catalog.non_declaration_callable_fragments()
    ));

    report.push_str("### Symbol Tree\n\n");
    for record in catalog
        .records()
        .iter()
        .filter(|record| record.parent.is_none())
    {
        append_symbol_tree(report, &catalog, record, 0);
    }
    report.push('\n');
}

fn fixture_metadata(path: &str) -> SourceFileMetadata {
    let root = repo_root();
    let relative_path = PathBuf::from(path);
    SourceFileMetadata {
        kind: SourceKind::Fixture,
        category: source_category_for_path(SourceKind::Fixture, Some(&relative_path)),
        absolute_path: Some(root.join(path)),
        virtual_source: None,
        root_path: Some(root),
        relative_path: Some(relative_path),
        priority: SOURCE_PRIORITY_FIXTURE,
    }
}

fn append_symbol_tree(
    report: &mut String,
    catalog: &SymbolCatalog<'_>,
    record: &SymbolRecord,
    depth: usize,
) {
    let indent = "  ".repeat(depth);
    report.push_str(&format!(
        "{indent}- {} `{}` id {} parent `{}` decl {} selection {}{} attrs {} modifiers `{}` docs {} preview `{}`\n",
        kind_name(record.kind),
        display_name(catalog, record),
        record.id.0,
        display_parent(record.parent),
        display_location(catalog, record.span),
        display_location(catalog, record.selection_span),
        display_detail(catalog, record),
        display_attributes(catalog, &record.attributes),
        display_spans(catalog, &record.modifiers),
        record.doc_comments.len(),
        doc_preview(catalog, record),
    ));

    for child in catalog
        .records()
        .iter()
        .filter(|child| child.parent == Some(record.id))
    {
        append_symbol_tree(report, catalog, child, depth + 1);
    }
}

fn kind_name(kind: SymbolKind) -> &'static str {
    match kind {
        SymbolKind::Class => "Class",
        SymbolKind::TypeParameter => "TypeParameter",
        SymbolKind::Enum => "Enum",
        SymbolKind::EnumMember => "EnumMember",
        SymbolKind::Typedef => "Typedef",
        SymbolKind::Function => "Function",
        SymbolKind::GlobalField => "GlobalField",
        SymbolKind::Field => "Field",
        SymbolKind::Method => "Method",
        SymbolKind::Constructor => "Constructor",
        SymbolKind::Destructor => "Destructor",
        SymbolKind::Parameter => "Parameter",
        SymbolKind::LocalVariable => "LocalVariable",
        SymbolKind::PreprocessorMacro => "PreprocessorMacro",
    }
}

fn display_name(catalog: &SymbolCatalog<'_>, record: &SymbolRecord) -> String {
    catalog
        .record_name(record)
        .map(escape_inline)
        .unwrap_or_else(|| "<unknown>".to_string())
}

fn display_parent(parent: Option<SymbolId>) -> String {
    parent
        .map(|id| id.0.to_string())
        .unwrap_or_else(|| "none".to_string())
}

fn display_detail(catalog: &SymbolCatalog<'_>, record: &SymbolRecord) -> String {
    let mut values = Vec::new();
    push_detail(catalog, &mut values, "type", record.detail.type_text);
    push_detail(
        catalog,
        &mut values,
        "return",
        record.detail.return_type_text,
    );
    push_detail(catalog, &mut values, "base", record.detail.base_type);
    push_detail(catalog, &mut values, "default", record.detail.default_text);
    push_detail(
        catalog,
        &mut values,
        "enum_value",
        record.detail.enum_value_text,
    );

    if values.is_empty() {
        String::new()
    } else {
        format!(" {}", values.join(" "))
    }
}

fn push_detail(
    catalog: &SymbolCatalog<'_>,
    values: &mut Vec<String>,
    label: &str,
    span: Option<TextSpan>,
) {
    if let Some(span) = span {
        values.push(format!("{label} `{}`", escape_inline(catalog.text(span))));
    }
}

fn display_spans(catalog: &SymbolCatalog<'_>, spans: &[TextSpan]) -> String {
    let text = spans
        .iter()
        .map(|span| escape_inline(catalog.text(*span)))
        .collect::<Vec<_>>();
    if text.is_empty() {
        "<none>".to_string()
    } else {
        text.join(" ")
    }
}

fn display_attributes(catalog: &SymbolCatalog<'_>, spans: &[TextSpan]) -> String {
    let names = spans
        .iter()
        .map(|span| {
            catalog
                .attribute_name(*span)
                .map(escape_inline)
                .unwrap_or_else(|| escape_inline(catalog.text(*span)))
        })
        .collect::<Vec<_>>();
    if names.is_empty() {
        "<none>".to_string()
    } else {
        format!("[{}]", names.join(", "))
    }
}

fn doc_preview(catalog: &SymbolCatalog<'_>, record: &SymbolRecord) -> String {
    record
        .doc_comments
        .first()
        .map(|comment| doc_text_preview(catalog.text(comment.span)))
        .unwrap_or_else(|| "<none>".to_string())
}

fn doc_text_preview(value: &str) -> String {
    let cleaned = value
        .lines()
        .map(clean_doc_line)
        .find(|line| !line.is_empty())
        .unwrap_or_else(|| value.trim().to_string());
    escape_inline(&cleaned)
}

fn clean_doc_line(line: &str) -> String {
    line.trim()
        .trim_start_matches("//!")
        .trim_start_matches("///<")
        .trim_start_matches("//")
        .trim_start_matches("/*!")
        .trim_start_matches("/**")
        .trim_start_matches("/*")
        .trim_start_matches('*')
        .trim_end_matches("*/")
        .trim()
        .to_string()
}

fn display_location(catalog: &SymbolCatalog<'_>, span: TextSpan) -> String {
    let (line, column) = line_column(catalog.source(), span.start);
    format!("{}:{} span {}..{}", line, column, span.start, span.end)
}

fn line_column(source: &str, offset: usize) -> (usize, usize) {
    let mut line = 1usize;
    let mut column = 1usize;

    for (index, value) in source.char_indices() {
        if index >= offset {
            break;
        }

        if value == '\n' {
            line += 1;
            column = 1;
        } else {
            column += 1;
        }
    }

    (line, column)
}

fn escape_inline(value: &str) -> String {
    value.replace('`', "\\`").replace('\n', "\\n")
}

fn display_optional_path(path: &Option<PathBuf>) -> String {
    path.as_ref()
        .map(|path| path.display().to_string())
        .unwrap_or_else(|| "<none>".to_string())
}
