use reforger_language_server::ast::{
    AstSourceFile, ClassDecl, ClassMember, Declaration, DocComment, MethodKind, TextValue,
};
use reforger_language_server::parser::parse_source;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/ast-fixtures.report.md";

struct Fixture {
    path: &'static str,
    source: &'static str,
}

fn main() -> Result<(), String> {
    let out_path = output_path()?;
    let report = render_report();

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&out_path, report)
        .map_err(|error| format!("Failed to write report {}: {error}", out_path.display()))?;

    println!("Wrote AST fixture report: {}", out_path.display());
    Ok(())
}

fn output_path() -> Result<PathBuf, String> {
    let mut args = env::args().skip(1);
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example ast_report -- [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn fixtures() -> [Fixture; 11] {
    [
        Fixture {
            path: "tools/fixtures/parser/core_types_declarations.c",
            source: include_str!("../../tools/fixtures/parser/core_types_declarations.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/attributes_rpc_workbench.c",
            source: include_str!("../../tools/fixtures/parser/attributes_rpc_workbench.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/modded_game_mode_members.c",
            source: include_str!("../../tools/fixtures/parser/modded_game_mode_members.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/preprocessor_directives.c",
            source: include_str!("../../tools/fixtures/parser/preprocessor_directives.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_network_component.c",
            source: include_str!("../../tools/fixtures/parser/game_building_network_component.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_provider_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_building_provider_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editable_group_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_editable_group_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editor_preview_params.c",
            source: include_str!("../../tools/fixtures/parser/game_editor_preview_params.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c",
            source: include_str!(
                "../../tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c"
            ),
        },
        Fixture {
            path: "tools/fixtures/parser/game_optional_semicolon_shapes.c",
            source: include_str!("../../tools/fixtures/parser/game_optional_semicolon_shapes.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_field_initializer_call_shapes.c",
            source: include_str!(
                "../../tools/fixtures/parser/game_field_initializer_call_shapes.c"
            ),
        },
    ]
}

fn render_report() -> String {
    let mut report = String::new();
    report.push_str("# AST Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example ast_report`.\n\n");
    report.push_str("This report shows source-backed declaration extraction from committed parser fixtures. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures() {
        append_fixture_report(&mut report, fixture);
    }

    report
}

fn append_fixture_report(report: &mut String, fixture: Fixture) {
    let parse = parse_source(fixture.source);
    let ast = AstSourceFile::new(fixture.source, &parse);
    let declarations = ast.declarations();

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str("### Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!(
        "| Parse diagnostics | {} |\n",
        parse.diagnostics.len()
    ));
    report.push_str(&format!(
        "| Top-level declarations | {} |\n\n",
        declarations.len()
    ));

    if !parse.diagnostics.is_empty() {
        report.push_str("### Parse Diagnostics\n\n");
        report.push_str("| Message | Span |\n");
        report.push_str("| --- | --- |\n");
        for diagnostic in &parse.diagnostics {
            report.push_str(&format!(
                "| `{}` | {}..{} |\n",
                escape_table(&diagnostic.message),
                diagnostic.span.start,
                diagnostic.span.end
            ));
        }
        report.push('\n');
    }

    report.push_str("### Declarations\n\n");
    if declarations.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    for declaration in declarations {
        append_declaration(report, declaration);
    }
    report.push('\n');
}

fn append_declaration(report: &mut String, declaration: Declaration<'_, '_>) {
    match declaration {
        Declaration::Class(class) => {
            report.push_str(&format!(
                "- Class `{}` span {}..{}",
                display_value(class.name()),
                class.span().start,
                class.span().end
            ));
            if let Some(base_type) = class.base_type() {
                report.push_str(&format!(" base `{}`", escape_inline(base_type.text())));
            }
            append_doc_comments(report, class.doc_comments());
            append_counts(report, class.attributes().len(), class.modifiers());
            report.push('\n');

            for member in class.members() {
                append_member(report, class, member);
            }
        }
        Declaration::Enum(enum_decl) => {
            let member_names = enum_decl
                .members()
                .into_iter()
                .filter_map(display_enum_member)
                .collect::<Vec<_>>();
            report.push_str(&format!(
                "- Enum `{}` span {}..{} members `{}`",
                display_value(enum_decl.name()),
                enum_decl.span().start,
                enum_decl.span().end,
                member_names.join(", ")
            ));
            append_doc_comments(report, enum_decl.doc_comments());
            append_counts(report, enum_decl.attributes().len(), Vec::new());
            report.push('\n');
        }
        Declaration::Typedef(typedef_decl) => {
            let span = typedef_decl.text_span();
            report.push_str(&format!(
                "- Typedef `{}` span {}..{}",
                display_value(typedef_decl.name()),
                span.start,
                span.end
            ));
            append_doc_comments(report, typedef_decl.doc_comments());
            report.push('\n');
        }
        Declaration::Function(function) => {
            report.push_str(&format!(
                "- Function `{}` returns `{}` span {}..{}",
                display_value(function.name()),
                display_value(function.return_type_text()),
                function.span().start,
                function.span().end
            ));
            append_doc_comments(report, function.doc_comments());
            append_counts(report, function.attributes().len(), function.modifiers());
            report.push('\n');
            append_parameters(report, "  ", function.parameters());
            append_parameter_fragments(report, "  ", function.parameter_fragments());
        }
        Declaration::Field(field) => {
            report.push_str(&format!(
                "- Global Field `{}` type `{}` span {}..{}",
                display_value(field.name()),
                display_value(field.type_text()),
                field.span().start,
                field.span().end
            ));
            append_doc_comments(report, field.doc_comments());
            append_counts(report, field.attributes().len(), field.modifiers());
            report.push('\n');
        }
    }
}

fn append_member(report: &mut String, class: ClassDecl<'_, '_>, member: ClassMember<'_, '_>) {
    match member {
        ClassMember::Field(field) => {
            report.push_str(&format!(
                "  - Field `{}` type `{}` span {}..{}",
                display_value(field.name()),
                display_value(field.type_text()),
                field.span().start,
                field.span().end
            ));
            append_doc_comments(report, field.doc_comments());
            append_counts(report, field.attributes().len(), field.modifiers());
            report.push('\n');
        }
        ClassMember::Method(method) => {
            let label = match class.classify_method(method) {
                MethodKind::Method => "Method",
                MethodKind::Constructor => "Constructor",
                MethodKind::Destructor => "Destructor",
            };
            let name_prefix = if class.classify_method(method) == MethodKind::Destructor {
                "~"
            } else {
                ""
            };
            report.push_str(&format!(
                "  - {label} `{name_prefix}{}` returns `{}` params {} span {}..{}",
                display_value(method.name()),
                display_value(method.return_type_text()),
                method.parameters().len(),
                method.span().start,
                method.span().end
            ));
            append_doc_comments(report, method.doc_comments());
            append_counts(report, method.attributes().len(), method.modifiers());
            report.push('\n');
            append_parameters(report, "    ", method.parameters());
            append_parameter_fragments(report, "    ", method.parameter_fragments());
        }
        ClassMember::Empty(empty) => {
            report.push_str(&format!(
                "  - Empty declaration span {}..{}\n",
                empty.span().start,
                empty.span().end
            ));
        }
    }
}

fn append_parameters(
    report: &mut String,
    indent: &str,
    parameters: Vec<reforger_language_server::ast::Parameter<'_, '_>>,
) {
    for parameter in parameters {
        let modifiers = parameter
            .modifiers()
            .into_iter()
            .map(|modifier| escape_inline(modifier.text()).to_string())
            .collect::<Vec<_>>();
        report.push_str(&format!(
            "{indent}- Parameter `{}` type `{}` default `{}` modifiers `{}` span {}..{}\n",
            display_value(parameter.name()),
            display_value(parameter.type_text()),
            display_value(parameter.default_text()),
            modifiers.join(" "),
            parameter.span().start,
            parameter.span().end
        ));
    }
}

fn append_parameter_fragments(
    report: &mut String,
    indent: &str,
    fragments: Vec<reforger_language_server::ast::Parameter<'_, '_>>,
) {
    for fragment in fragments {
        report.push_str(&format!(
            "{indent}- Non-declaration callable fragment `{}` span {}..{}\n",
            display_value(fragment.text()),
            fragment.span().start,
            fragment.span().end
        ));
    }
}

fn append_counts(report: &mut String, attribute_count: usize, modifiers: Vec<TextValue<'_>>) {
    let modifier_text = modifiers
        .into_iter()
        .map(|modifier| escape_inline(modifier.text()).to_string())
        .collect::<Vec<_>>();
    report.push_str(&format!(
        " attrs {} modifiers `{}`",
        attribute_count,
        modifier_text.join(" ")
    ));
}

fn append_doc_comments(report: &mut String, comments: Vec<DocComment<'_>>) {
    let preview = comments
        .first()
        .map(|comment| first_line_preview(comment.text()))
        .unwrap_or_else(|| "<none>".to_string());
    report.push_str(&format!(
        " docs {} preview `{}`",
        comments.len(),
        escape_inline(&preview)
    ));
}

fn display_enum_member(
    member: reforger_language_server::ast::EnumMember<'_, '_>,
) -> Option<String> {
    let name = member.name()?;
    Some(match member.value_text() {
        Some(value) => format!(
            "{} = {}",
            escape_inline(name.text()),
            escape_inline(value.text())
        ),
        None => escape_inline(name.text()).to_string(),
    })
}

fn display_value(value: Option<TextValue<'_>>) -> String {
    value
        .map(|value| escape_inline(value.text()).to_string())
        .unwrap_or_else(|| "<unknown>".to_string())
}

fn escape_inline(value: &str) -> String {
    value.replace('`', "\\`").replace('\n', "\\n")
}

fn first_line_preview(value: &str) -> String {
    value.lines().next().unwrap_or("").trim().to_string()
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|")
}
