use reforger_language_server::parser::parse_source;
use reforger_language_server::syntax::{SyntaxElement, SyntaxKind, SyntaxNode};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/expression-corpus.report.md";
const DEFAULT_STORAGE_RELATIVE_PATH: &str =
    "Code/User/globalStorage/undefined_publisher.reforger-sript-tools/game-data/scripts";
const MAX_ROWS: usize = 50;

struct Args {
    scripts_path: PathBuf,
    out_path: PathBuf,
}

#[derive(Default)]
struct FileStats {
    path: PathBuf,
    diagnostics: usize,
    error_nodes: usize,
    expression_depth: usize,
    named_arguments: usize,
    initializer_expressions: usize,
    statement_nodes: usize,
    expression_nodes: usize,
}

fn main() -> Result<(), String> {
    let args = parse_args()?;
    let report = render_report(&args.scripts_path)?;

    if let Some(parent) = args.out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }
    fs::write(&args.out_path, report).map_err(|error| {
        format!(
            "Failed to write expression corpus report {}: {error}",
            args.out_path.display()
        )
    })?;

    println!(
        "Wrote expression corpus report: {}",
        args.out_path.display()
    );
    Ok(())
}

fn parse_args() -> Result<Args, String> {
    let mut scripts = None;
    let mut out = None;
    let mut args = env::args().skip(1);

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--scripts" => {
                let Some(value) = args.next() else {
                    return Err("--scripts requires a path".to_string());
                };
                scripts = Some(PathBuf::from(value));
            }
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example expression_corpus_report -- [--scripts <path>] [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(Args {
        scripts_path: scripts.unwrap_or_else(default_scripts_path),
        out_path: resolve_repo_path(out, DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn render_report(scripts_path: &Path) -> Result<String, String> {
    if !scripts_path.is_dir() {
        return Err(format!(
            "Scripts folder does not exist or is not a folder: {}",
            scripts_path.display()
        ));
    }

    let mut files = Vec::new();
    collect_script_files(scripts_path, &mut files)?;
    files.sort();

    let mut total_bytes = 0usize;
    let mut total_tokens = 0usize;
    let mut total_diagnostics = 0usize;
    let mut lossy_files = 0usize;
    let mut kind_counts = BTreeMap::<String, usize>::new();
    let mut file_stats = Vec::<FileStats>::new();

    for file in &files {
        let bytes = fs::read(file)
            .map_err(|error| format!("Failed to read {}: {error}", file.display()))?;
        total_bytes += bytes.len();
        let source = String::from_utf8_lossy(&bytes);
        if matches!(source, Cow::Owned(_)) {
            lossy_files += 1;
        }
        let source = source.into_owned();
        let parse = parse_source(&source);

        let mut stats = FileStats {
            path: file.clone(),
            diagnostics: parse.diagnostics.len(),
            expression_depth: max_expression_depth(&parse.root, 0),
            ..FileStats::default()
        };
        total_tokens += parse.root.token_count();
        total_diagnostics += parse.diagnostics.len();
        collect_stats(&parse.root, &mut kind_counts, &mut stats);
        file_stats.push(stats);
    }

    let mut report = String::new();
    report.push_str("# Expression Corpus Report\n\n");
    report.push_str(
        "> Human-review output generated by `node tools/expression-corpus-report.mjs`.\n\n",
    );
    report.push_str("This report summarizes statement/expression parser coverage across game-data scripts. It is review data only; Workbench remains compiler truth.\n\n");

    report.push_str("## Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Source path | `{}` |\n", scripts_path.display()));
    report.push_str(&format!(
        "| Scan timestamp unix seconds | {} |\n",
        timestamp()
    ));
    report.push_str(&format!("| `.c` files | {} |\n", files.len()));
    report.push_str(&format!("| Bytes | {} |\n", total_bytes));
    report.push_str(&format!("| Tokens preserved | {} |\n", total_tokens));
    report.push_str(&format!("| Diagnostics | {} |\n", total_diagnostics));
    report.push_str(&format!("| Files decoded lossily | {} |\n\n", lossy_files));

    append_counts(
        &mut report,
        "Statement / Expression Kind Frequency",
        &kind_counts,
    );
    append_top_files(
        &mut report,
        scripts_path,
        "Top Files By Expression Depth",
        &file_stats,
        |stats| stats.expression_depth,
    );
    append_top_files(
        &mut report,
        scripts_path,
        "Top Files By Named Arguments",
        &file_stats,
        |stats| stats.named_arguments,
    );
    append_top_files(
        &mut report,
        scripts_path,
        "Top Files By Initializer Expressions",
        &file_stats,
        |stats| stats.initializer_expressions,
    );
    append_top_files(
        &mut report,
        scripts_path,
        "Top Files By Recovery/Error Nodes",
        &file_stats,
        |stats| stats.error_nodes,
    );

    Ok(report)
}

fn collect_script_files(folder: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(folder)
        .map_err(|error| format!("Failed to read folder {}: {error}", folder.display()))?
    {
        let entry = entry
            .map_err(|error| format!("Failed to read entry in {}: {error}", folder.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_script_files(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "c") {
            files.push(path);
        }
    }
    Ok(())
}

fn collect_stats(
    node: &SyntaxNode,
    kind_counts: &mut BTreeMap<String, usize>,
    stats: &mut FileStats,
) {
    if is_statement_or_expression_kind(node.kind) {
        *kind_counts.entry(format!("{:?}", node.kind)).or_default() += 1;
    }
    if is_statement_kind(node.kind) {
        stats.statement_nodes += 1;
    }
    if is_expression_kind(node.kind) {
        stats.expression_nodes += 1;
    }
    match node.kind {
        SyntaxKind::Error => stats.error_nodes += 1,
        SyntaxKind::NamedArgument => stats.named_arguments += 1,
        SyntaxKind::InitializerExpression => stats.initializer_expressions += 1,
        _ => {}
    }
    for child in &node.children {
        if let SyntaxElement::Node(child) = child {
            collect_stats(child, kind_counts, stats);
        }
    }
}

fn append_counts(report: &mut String, title: &str, counts: &BTreeMap<String, usize>) {
    report.push_str(&format!("## {title}\n\n"));
    report.push_str("| Syntax kind | Count |\n");
    report.push_str("| --- | ---: |\n");
    for (kind, count) in counts.iter().take(MAX_ROWS) {
        report.push_str(&format!("| `{kind}` | {count} |\n"));
    }
    report.push('\n');
}

fn append_top_files<F>(
    report: &mut String,
    root: &Path,
    title: &str,
    file_stats: &[FileStats],
    metric: F,
) where
    F: Fn(&FileStats) -> usize,
{
    let mut rows = file_stats
        .iter()
        .filter(|stats| metric(stats) > 0)
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| {
        metric(right)
            .cmp(&metric(left))
            .then_with(|| left.path.cmp(&right.path))
    });

    report.push_str(&format!("## {title}\n\n"));
    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| File | Value | Statements | Expressions | Diagnostics |\n");
    report.push_str("| --- | ---: | ---: | ---: | ---: |\n");
    for stats in rows.into_iter().take(25) {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            relative_path(root, &stats.path),
            metric(stats),
            stats.statement_nodes,
            stats.expression_nodes,
            stats.diagnostics
        ));
    }
    report.push('\n');
}

fn max_expression_depth(node: &SyntaxNode, current: usize) -> usize {
    let next = if is_expression_kind(node.kind) {
        current + 1
    } else {
        current
    };
    node.children
        .iter()
        .filter_map(|child| match child {
            SyntaxElement::Node(child) => Some(max_expression_depth(child, next)),
            SyntaxElement::Token(_) => None,
        })
        .max()
        .unwrap_or(next)
}

fn is_statement_or_expression_kind(kind: SyntaxKind) -> bool {
    is_statement_kind(kind) || is_expression_kind(kind)
}

fn is_statement_kind(kind: SyntaxKind) -> bool {
    matches!(
        kind,
        SyntaxKind::IfStatement
            | SyntaxKind::ForStatement
            | SyntaxKind::ForeachStatement
            | SyntaxKind::WhileStatement
            | SyntaxKind::DoWhileStatement
            | SyntaxKind::SwitchStatement
            | SyntaxKind::CaseClause
            | SyntaxKind::DefaultClause
            | SyntaxKind::ReturnStatement
            | SyntaxKind::BreakStatement
            | SyntaxKind::ContinueStatement
            | SyntaxKind::DeleteStatement
            | SyntaxKind::ThreadStatement
            | SyntaxKind::EmptyStatement
            | SyntaxKind::LocalDeclStatement
            | SyntaxKind::ExpressionStatement
            | SyntaxKind::ForHeader
            | SyntaxKind::ForInitializer
            | SyntaxKind::ForCondition
            | SyntaxKind::ForIncrement
    )
}

fn is_expression_kind(kind: SyntaxKind) -> bool {
    matches!(
        kind,
        SyntaxKind::Expression
            | SyntaxKind::NameExpression
            | SyntaxKind::LiteralExpression
            | SyntaxKind::ParenthesizedExpression
            | SyntaxKind::UnaryExpression
            | SyntaxKind::BinaryExpression
            | SyntaxKind::AssignmentExpression
            | SyntaxKind::TernaryExpression
            | SyntaxKind::CallExpression
            | SyntaxKind::ArgumentList
            | SyntaxKind::NamedArgument
            | SyntaxKind::MemberAccessExpression
            | SyntaxKind::IndexExpression
            | SyntaxKind::CastExpression
            | SyntaxKind::PostfixExpression
            | SyntaxKind::NewExpression
            | SyntaxKind::InitializerExpression
    )
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

fn timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

fn default_scripts_path() -> PathBuf {
    if let Some(app_data) = env::var_os("APPDATA") {
        PathBuf::from(app_data).join(DEFAULT_STORAGE_RELATIVE_PATH)
    } else {
        PathBuf::from(DEFAULT_STORAGE_RELATIVE_PATH)
    }
}

fn resolve_repo_path(path: Option<PathBuf>, default_relative_path: &str) -> PathBuf {
    match path {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(default_relative_path),
    }
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}
