use reforger_language_server::index::{GlobalSymbolId, SymbolIndex};
use reforger_language_server::index_build::{
    build_index, IndexBuildConfig, IndexBuildCounts, IndexSourceRoot,
};
use reforger_language_server::model::{
    SourceKind, SymbolKind, SOURCE_PRIORITY_GAME_DATA, SOURCE_PRIORITY_WORKSPACE,
};
use reforger_language_server::symbol_display::SymbolDisplay;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/index-overlay.report.md";
const DEFAULT_STORAGE_RELATIVE_PATH: &str =
    "Code/User/globalStorage/undefined_publisher.reforger-sript-tools/game-data/scripts";
const MAX_ROWS: usize = 100;
const MAX_DECLARATIONS_PER_ROW: usize = 8;
const MAX_SIGNATURES_PER_METHOD_GROUP: usize = 3;

struct Args {
    scripts_path: PathBuf,
    workspace_path: PathBuf,
    out_path: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum DuplicateClassification {
    WorkspaceOverlay,
    TypedefFunctionDelegatePair,
    TypedefClassWrapperPattern,
    GeneratedVsSourceDuplicate,
    SuspiciousSameKindDuplicate,
    MixedKindDuplicate,
}

fn main() -> Result<(), String> {
    let args = parse_args()?;
    let report = render_report(&args.scripts_path, &args.workspace_path)?;

    if let Some(parent) = args.out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&args.out_path, report).map_err(|error| {
        format!(
            "Failed to write index overlay report {}: {error}",
            args.out_path.display()
        )
    })?;

    println!("Wrote index overlay report: {}", args.out_path.display());
    Ok(())
}

fn parse_args() -> Result<Args, String> {
    let mut args = env::args().skip(1);
    let mut scripts: Option<PathBuf> = None;
    let mut workspace: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--scripts" => {
                scripts = Some(take_path(&mut args, "--scripts")?);
            }
            "--workspace" => {
                workspace = Some(take_path(&mut args, "--workspace")?);
            }
            "--out" => {
                out = Some(take_path(&mut args, "--out")?);
            }
            "--help" | "-h" => {
                print_usage();
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    let Some(workspace_path) = workspace else {
        return Err("--workspace <path> is required".to_string());
    };

    Ok(Args {
        scripts_path: scripts.unwrap_or_else(default_scripts_path),
        workspace_path,
        out_path: resolve_repo_path(out, DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn take_path(args: &mut impl Iterator<Item = String>, label: &str) -> Result<PathBuf, String> {
    args.next()
        .map(PathBuf::from)
        .ok_or_else(|| format!("{label} requires a path"))
}

fn print_usage() {
    println!(
        "Usage: node tools/index-overlay-report.mjs --workspace <path> [--scripts <path>] [--out <path>]"
    );
}

fn default_scripts_path() -> PathBuf {
    if let Some(app_data) = env::var_os("APPDATA") {
        PathBuf::from(app_data).join(DEFAULT_STORAGE_RELATIVE_PATH)
    } else {
        PathBuf::from(DEFAULT_STORAGE_RELATIVE_PATH)
    }
}

fn resolve_repo_path(path: Option<PathBuf>, default_relative_path: &str) -> PathBuf {
    match path {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(default_relative_path),
    }
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn render_report(scripts_path: &Path, workspace_path: &Path) -> Result<String, String> {
    let build_result = build_index(&IndexBuildConfig {
        roots: vec![
            IndexSourceRoot::new(
                scripts_path,
                SourceKind::GameData,
                SOURCE_PRIORITY_GAME_DATA,
            ),
            IndexSourceRoot::new(
                workspace_path,
                SourceKind::Workspace,
                SOURCE_PRIORITY_WORKSPACE,
            ),
        ],
    })?;
    let index = build_result.index;
    let summary = build_result.summary;
    let totals = &summary.by_source_kind;

    let mut report = String::new();
    report.push_str("# Index Overlay Report\n\n");
    report
        .push_str("> Human-review output generated by `node tools/index-overlay-report.mjs`.\n\n");
    report.push_str("This report indexes game-data scripts plus an explicit workspace script folder. It is lookup review data only; Workbench remains compiler truth.\n\n");
    report.push_str("## Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!(
        "| Game-data scripts | `{}` |\n",
        scripts_path.display()
    ));
    report.push_str(&format!(
        "| Workspace scripts | `{}` |\n",
        workspace_path.display()
    ));
    report.push_str(&format!(
        "| Scan timestamp unix seconds | {} |\n",
        timestamp()
    ));
    report.push_str(&format!("| Indexed files | {} |\n", index.files().len()));
    report.push_str(&format!(
        "| Indexed symbols | {} |\n\n",
        index.symbols().len()
    ));

    append_source_counts(&mut report, totals);
    append_parse_diagnostic_snippets(&mut report, scripts_path, workspace_path, &summary.totals);
    append_workspace_duplicate_classification_summary(&mut report, &index);
    append_workspace_duplicate_top_level_names(&mut report, &index);
    append_workspace_kind_specific_preferred_top_level(&mut report, &index);
    append_workspace_preferred_failures(&mut report, &index);
    append_workspace_preferred_top_level_samples(&mut report, &index);
    append_workspace_only_top_level_samples(&mut report, &index);
    append_workspace_method_overlay_samples(&mut report, &index);
    append_workspace_method_group_samples(&mut report, &index);

    Ok(report)
}

fn append_source_counts(report: &mut String, totals: &BTreeMap<SourceKind, IndexBuildCounts>) {
    report.push_str("## Source Counts\n\n");
    report.push_str("| Source kind | Files scanned | Bytes | Lossy files | Parse diagnostics | Indexed files | Indexed symbols |\n");
    report.push_str("| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n");
    for kind in [SourceKind::GameData, SourceKind::Workspace] {
        let source_totals = totals.get(&kind);
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | {} |\n",
            kind.as_str(),
            source_totals.map(|totals| totals.files).unwrap_or(0),
            source_totals.map(|totals| totals.bytes).unwrap_or(0),
            source_totals.map(|totals| totals.lossy_files).unwrap_or(0),
            source_totals
                .map(|totals| totals.parse_diagnostics)
                .unwrap_or(0),
            source_totals
                .map(|totals| totals.indexed_files)
                .unwrap_or(0),
            source_totals
                .map(|totals| totals.indexed_symbols)
                .unwrap_or(0)
        ));
    }
    report.push('\n');
}

fn append_parse_diagnostic_snippets(
    report: &mut String,
    scripts_path: &Path,
    workspace_path: &Path,
    totals: &IndexBuildCounts,
) {
    report.push_str("## Parse Diagnostic Snippets\n\n");
    if totals.parse_diagnostic_details.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    for detail in &totals.parse_diagnostic_details {
        report.push_str(&format!(
            "### `{}`\n\n",
            escape_inline(&display_overlay_relative_path(
                scripts_path,
                workspace_path,
                &detail.path
            ))
        ));
        report.push_str(&format!(
            "- `{}` at {}:{} span {}..{}\n\n",
            escape_inline(&detail.message),
            detail.line,
            detail.column,
            detail.span.start,
            detail.span.end
        ));
        report.push_str("````enforce\n");
        report.push_str(&detail.snippet);
        report.push_str("````\n\n");
    }
}

fn append_workspace_duplicate_classification_summary(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Duplicate Classification Summary\n\n");
    report.push_str("These buckets classify only duplicate top-level names that involve workspace symbols. They are review labels, not semantic merge rules.\n\n");

    let mut counts = BTreeMap::<String, usize>::new();
    for (_, symbols) in workspace_duplicate_top_level_rows(index) {
        *counts
            .entry(duplicate_classification_label(classify_duplicate(index, &symbols)).to_string())
            .or_default() += 1;
    }

    if counts.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Classification | Groups |\n");
    report.push_str("| --- | ---: |\n");
    for classification in [
        DuplicateClassification::WorkspaceOverlay,
        DuplicateClassification::TypedefFunctionDelegatePair,
        DuplicateClassification::TypedefClassWrapperPattern,
        DuplicateClassification::GeneratedVsSourceDuplicate,
        DuplicateClassification::SuspiciousSameKindDuplicate,
        DuplicateClassification::MixedKindDuplicate,
    ] {
        let label = duplicate_classification_label(classification);
        report.push_str(&format!(
            "| `{}` | {} |\n",
            label,
            counts.get(label).copied().unwrap_or(0)
        ));
    }
    report.push('\n');
}

fn append_workspace_duplicate_top_level_names(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Duplicate Top-Level Names\n\n");
    let rows = workspace_duplicate_top_level_rows(index);
    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("Generic preferred top-level ordering is shown for conflict/debug review only. It may compare unrelated declaration kinds such as class and typedef.\n\n");
    report.push_str("| Name | Classification | Generic preferred declaration | Declarations |\n");
    report.push_str("| --- | --- | --- | --- |\n");
    for (name, symbols) in rows.into_iter().take(MAX_ROWS) {
        let classification = duplicate_classification_label(classify_duplicate(index, &symbols));
        let preferred = index
            .preferred_top_level_symbols_for_name(&name)
            .first()
            .copied()
            .map(|id| display_symbol_location(index, id))
            .unwrap_or_else(|| "<none>".to_string());
        let declarations = display_declarations(index, &symbols);
        report.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            escape_table(&name),
            classification,
            preferred,
            declarations
        ));
    }
    report.push('\n');
}

fn append_workspace_kind_specific_preferred_top_level(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Kind-Specific Preferred Top-Level\n\n");
    report.push_str("These rows use kind-specific preferred lookup. This is the authoritative overlay preference view for classes, typedefs, and functions with the same name.\n\n");
    let rows = workspace_duplicate_top_level_rows(index);
    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Name | Preferred class | Preferred typedef | Preferred function |\n");
    report.push_str("| --- | --- | --- | --- |\n");
    for (name, _) in rows.into_iter().take(MAX_ROWS) {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            escape_table(&name),
            display_preferred_kind(index, index.preferred_classes_by_name(&name)),
            display_preferred_kind(index, index.preferred_typedefs_by_name(&name)),
            display_preferred_kind(index, index.preferred_functions_by_name(&name))
        ));
    }
    report.push('\n');
}

fn append_workspace_preferred_top_level_samples(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Generic Preferred Top-Level Samples\n\n");
    report.push_str("These samples keep the generic cross-kind preferred ordering visible for conflict/debug review. Use the kind-specific section above for class, typedef, and function decisions.\n\n");
    let mut rows = Vec::new();
    for (name, symbols) in workspace_duplicate_top_level_rows(index) {
        let Some(preferred) = index
            .preferred_top_level_symbols_for_name(&name)
            .first()
            .copied()
        else {
            continue;
        };
        if is_source_kind(index, preferred, SourceKind::Workspace) {
            rows.push((name, preferred, symbols));
        }
    }

    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Name | Preferred workspace declaration | All declarations |\n");
    report.push_str("| --- | --- | --- |\n");
    for (name, preferred, symbols) in rows.into_iter().take(MAX_ROWS) {
        report.push_str(&format!(
            "| `{}` | {} | {} |\n",
            escape_table(&name),
            display_symbol_location(index, preferred),
            display_declarations(index, &symbols)
        ));
    }
    report.push('\n');
}

fn append_workspace_only_top_level_samples(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace-Only Top-Level Samples\n\n");
    report.push_str("These rows show workspace top-level declarations whose names do not currently collide with game data. They help review new workspace symbols in the overlay fixture.\n\n");

    let mut rows = index
        .symbols()
        .iter()
        .filter(|symbol| symbol.parent.is_none())
        .filter(|symbol| is_source_kind(index, symbol.id, SourceKind::Workspace))
        .filter_map(|symbol| {
            let name = symbol.name.as_ref()?;
            let top_level = index.top_level_symbols_for_name(name);
            if has_source_kind(index, top_level, SourceKind::GameData) {
                return None;
            }
            Some((name.clone(), symbol.id))
        })
        .collect::<Vec<_>>();
    rows.sort_by(|left, right| left.0.cmp(&right.0));

    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Name | Declaration |\n");
    report.push_str("| --- | --- |\n");
    for (name, id) in rows.into_iter().take(MAX_ROWS) {
        report.push_str(&format!(
            "| `{}` | {} |\n",
            escape_table(&name),
            display_symbol_location(index, id)
        ));
    }
    report.push('\n');
}

fn append_workspace_preferred_failures(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Preferred Failures\n\n");
    report.push_str("These rows would indicate a workspace-involved kind-specific duplicate or method overlay where the preferred result is not from the workspace source kind. Generic cross-kind top-level ordering is not used for failure auditing.\n\n");

    let mut top_level_failures = Vec::new();
    for (name, _) in workspace_duplicate_top_level_rows(index) {
        for (kind, symbols, preferred) in kind_specific_preferred_rows(index, &name) {
            if !has_source_kind(index, &symbols, SourceKind::Workspace) || symbols.len() < 2 {
                continue;
            }
            let Some(preferred) = preferred else {
                continue;
            };
            if !is_source_kind(index, preferred, SourceKind::Workspace) {
                top_level_failures.push((name.clone(), kind, preferred, symbols));
            }
        }
    }

    let mut method_failures = Vec::new();
    for ((owner, name), symbols) in index.method_owner_name_groups() {
        if !has_source_kind(index, symbols, SourceKind::Workspace)
            || !has_source_kind(index, symbols, SourceKind::GameData)
        {
            continue;
        }
        let Some(preferred) = index.preferred_from_symbols(symbols).first().copied() else {
            continue;
        };
        if !is_source_kind(index, preferred, SourceKind::Workspace) {
            method_failures.push((owner.clone(), name.clone(), preferred, symbols.clone()));
        }
    }

    if top_level_failures.is_empty() && method_failures.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    if !top_level_failures.is_empty() {
        report.push_str("### Kind-Specific Top-Level Failures\n\n");
        report.push_str("| Name | Kind | Preferred declaration | All declarations for kind |\n");
        report.push_str("| --- | --- | --- | --- |\n");
        for (name, kind, preferred, symbols) in top_level_failures.into_iter().take(MAX_ROWS) {
            report.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                escape_table(&name),
                kind,
                display_symbol_location(index, preferred),
                display_declarations(index, &symbols)
            ));
        }
        report.push('\n');
    }

    if !method_failures.is_empty() {
        report.push_str("### Method Overlay Failures\n\n");
        report.push_str("| Owner.Method | Preferred declaration | Overloads |\n");
        report.push_str("| --- | --- | --- |\n");
        for (owner, name, preferred, symbols) in method_failures.into_iter().take(MAX_ROWS) {
            report.push_str(&format!(
                "| `{}` | {} | {} |\n",
                escape_table(&format!("{owner}.{name}")),
                display_symbol_location(index, preferred),
                display_declarations(index, &symbols)
            ));
        }
        report.push('\n');
    }
}

fn display_preferred_kind(index: &SymbolIndex, preferred: Vec<GlobalSymbolId>) -> String {
    preferred
        .first()
        .copied()
        .map(|id| display_symbol_location(index, id))
        .unwrap_or_else(|| "<none>".to_string())
}

fn kind_specific_preferred_rows(
    index: &SymbolIndex,
    name: &str,
) -> Vec<(&'static str, Vec<GlobalSymbolId>, Option<GlobalSymbolId>)> {
    vec![
        (
            "Class",
            index.classes_by_name(name).to_vec(),
            index.preferred_classes_by_name(name).first().copied(),
        ),
        (
            "Typedef",
            index.typedefs_by_name(name).to_vec(),
            index.preferred_typedefs_by_name(name).first().copied(),
        ),
        (
            "Function",
            index.functions_by_name(name).to_vec(),
            index.preferred_functions_by_name(name).first().copied(),
        ),
    ]
}

fn append_workspace_method_overlay_samples(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Method Overlay Samples\n\n");
    let mut rows = Vec::new();
    for ((owner, name), symbols) in index.method_owner_name_groups() {
        if !has_source_kind(index, symbols, SourceKind::Workspace)
            || !has_source_kind(index, symbols, SourceKind::GameData)
        {
            continue;
        }
        let preferred = index.preferred_from_symbols(symbols).first().copied();
        rows.push((owner.clone(), name.clone(), symbols.clone(), preferred));
    }

    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Owner.Method | Preferred declaration | Overloads |\n");
    report.push_str("| --- | --- | --- |\n");
    for (owner, name, symbols, preferred) in rows.into_iter().take(MAX_ROWS) {
        let preferred = preferred
            .map(|id| display_symbol_location(index, id))
            .unwrap_or_else(|| "<none>".to_string());
        report.push_str(&format!(
            "| `{}` | {} | {} |\n",
            escape_table(&format!("{owner}.{name}")),
            preferred,
            display_declarations(index, &symbols)
        ));
    }
    report.push('\n');
}

fn append_workspace_method_group_samples(report: &mut String, index: &SymbolIndex) {
    report.push_str("## Workspace Method Group Samples\n\n");
    report.push_str("These rows show owner/name method groups with workspace methods, including workspace-only overload groups that do not appear in the overlay-only method section above.\n\n");

    let mut rows = Vec::new();
    for ((owner, name), symbols) in index.method_owner_name_groups() {
        if !has_source_kind(index, symbols, SourceKind::Workspace) {
            continue;
        }
        rows.push((owner.clone(), name.clone(), symbols.clone()));
    }
    rows.sort_by(|left, right| {
        left.0
            .cmp(&right.0)
            .then_with(|| left.1.cmp(&right.1))
            .then_with(|| right.2.len().cmp(&left.2.len()))
    });

    if rows.is_empty() {
        report.push_str("None.\n\n");
        return;
    }

    report.push_str("| Owner.Method | Methods | Signatures |\n");
    report.push_str("| --- | ---: | --- |\n");
    for (owner, name, symbols) in rows.into_iter().take(MAX_ROWS) {
        report.push_str(&format!(
            "| `{}` | {} | `{}` |\n",
            escape_table(&format!("{owner}.{name}")),
            symbols.len(),
            escape_table(&method_signatures(index, &symbols).join("<br>"))
        ));
    }
    report.push('\n');
}

fn workspace_duplicate_top_level_rows(index: &SymbolIndex) -> Vec<(String, Vec<GlobalSymbolId>)> {
    let mut rows = Vec::new();
    for (name, symbols) in index.duplicate_top_level_names() {
        if has_source_kind(index, symbols, SourceKind::Workspace) {
            rows.push((name.to_string(), symbols.to_vec()));
        }
    }
    rows.sort_by(|left, right| left.0.cmp(&right.0));
    rows
}

fn has_source_kind(index: &SymbolIndex, symbols: &[GlobalSymbolId], kind: SourceKind) -> bool {
    symbols.iter().any(|id| is_source_kind(index, *id, kind))
}

fn is_source_kind(index: &SymbolIndex, id: GlobalSymbolId, kind: SourceKind) -> bool {
    index
        .file(id.file_id)
        .is_some_and(|file| file.metadata.kind == kind)
}

fn display_declarations(index: &SymbolIndex, symbols: &[GlobalSymbolId]) -> String {
    let mut declarations = symbols
        .iter()
        .take(MAX_DECLARATIONS_PER_ROW)
        .map(|id| display_symbol_location(index, *id))
        .collect::<Vec<_>>();
    if symbols.len() > MAX_DECLARATIONS_PER_ROW {
        declarations.push(format!(
            "... {} more",
            symbols.len() - MAX_DECLARATIONS_PER_ROW
        ));
    }
    declarations.join("<br>")
}

fn method_signatures(index: &SymbolIndex, ids: &[GlobalSymbolId]) -> Vec<String> {
    let mut signatures = ids
        .iter()
        .take(MAX_SIGNATURES_PER_METHOD_GROUP)
        .filter_map(|id| index.callable_signature(*id))
        .collect::<Vec<_>>();
    if ids.len() > MAX_SIGNATURES_PER_METHOD_GROUP {
        signatures.push(format!(
            "... {} more",
            ids.len() - MAX_SIGNATURES_PER_METHOD_GROUP
        ));
    }
    signatures
}

fn display_symbol_location(index: &SymbolIndex, id: GlobalSymbolId) -> String {
    let Some(symbol) = index.symbol(id) else {
        return format!("missing symbol {:?}", id);
    };
    let Some(file) = index.file(id.file_id) else {
        return format!("missing file {:?}", id.file_id);
    };
    let path = file
        .metadata
        .relative_path
        .as_ref()
        .or(file.metadata.absolute_path.as_ref())
        .map(|path| path.display().to_string())
        .unwrap_or_else(|| "<unknown-path>".to_string());
    let name = symbol.name.as_deref().unwrap_or("<unknown>");
    let detail = detail_text(index, id);
    format!(
        "{} `{}` in `{}` source `{}` priority {}{}",
        kind_name(symbol.kind),
        escape_table(name),
        escape_table(&path),
        file.metadata.kind.as_str(),
        file.metadata.priority,
        detail
    )
}

fn classify_duplicate(index: &SymbolIndex, symbols: &[GlobalSymbolId]) -> DuplicateClassification {
    if has_source_kind(index, symbols, SourceKind::Workspace)
        && has_source_kind(index, symbols, SourceKind::GameData)
    {
        return DuplicateClassification::WorkspaceOverlay;
    }

    let kinds = duplicate_kind_counts(index, symbols);
    let has_typedef = kinds.contains_key(&SymbolKind::Typedef);
    let has_function = kinds.contains_key(&SymbolKind::Function);
    let has_class = kinds.contains_key(&SymbolKind::Class);

    if has_typedef
        && has_function
        && symbols.iter().all(|id| {
            index.symbol(*id).is_some_and(|symbol| {
                matches!(symbol.kind, SymbolKind::Typedef | SymbolKind::Function)
            })
        })
    {
        return DuplicateClassification::TypedefFunctionDelegatePair;
    }

    if has_typedef
        && has_class
        && symbols.iter().all(|id| {
            index.symbol(*id).is_some_and(|symbol| {
                matches!(symbol.kind, SymbolKind::Typedef | SymbolKind::Class)
            })
        })
    {
        return DuplicateClassification::TypedefClassWrapperPattern;
    }

    if has_generated_and_source_paths(index, symbols) {
        return DuplicateClassification::GeneratedVsSourceDuplicate;
    }

    if kinds.values().any(|count| *count > 1) {
        return DuplicateClassification::SuspiciousSameKindDuplicate;
    }

    DuplicateClassification::MixedKindDuplicate
}

fn duplicate_kind_counts(
    index: &SymbolIndex,
    symbols: &[GlobalSymbolId],
) -> BTreeMap<SymbolKind, usize> {
    let mut counts = BTreeMap::new();
    for id in symbols {
        if let Some(symbol) = index.symbol(*id) {
            *counts.entry(symbol.kind).or_default() += 1;
        }
    }
    counts
}

fn has_generated_and_source_paths(index: &SymbolIndex, symbols: &[GlobalSymbolId]) -> bool {
    let mut has_generated = false;
    let mut has_non_generated = false;

    for id in symbols {
        let Some(file) = index.file(id.file_id) else {
            continue;
        };
        let path = file
            .metadata
            .relative_path
            .as_ref()
            .or(file.metadata.absolute_path.as_ref())
            .map(|path| path.to_string_lossy().replace('\\', "/").to_lowercase())
            .unwrap_or_default();
        if path.contains("/generated/") || path.starts_with("generated/") {
            has_generated = true;
        } else {
            has_non_generated = true;
        }
    }

    has_generated && has_non_generated
}

fn duplicate_classification_label(classification: DuplicateClassification) -> &'static str {
    match classification {
        DuplicateClassification::WorkspaceOverlay => "workspace overlay duplicate",
        DuplicateClassification::TypedefFunctionDelegatePair => "typedef + function delegate pair",
        DuplicateClassification::TypedefClassWrapperPattern => "typedef + class wrapper pattern",
        DuplicateClassification::GeneratedVsSourceDuplicate => {
            "generated vs non-generated duplicate"
        }
        DuplicateClassification::SuspiciousSameKindDuplicate => "suspicious same-kind duplicate",
        DuplicateClassification::MixedKindDuplicate => "mixed-kind duplicate",
    }
}

fn detail_text(index: &SymbolIndex, id: GlobalSymbolId) -> String {
    SymbolDisplay::for_symbol(index, id)
        .and_then(|display| display.detail)
        .map(|detail| format!(" detail `{}`", escape_table(&detail)))
        .unwrap_or_default()
}

fn display_overlay_relative_path(
    scripts_path: &Path,
    workspace_path: &Path,
    file: &Path,
) -> String {
    if let Ok(path) = file.strip_prefix(workspace_path) {
        return format!("workspace:{}", path.display());
    }
    if let Ok(path) = file.strip_prefix(scripts_path) {
        return format!("game-data:{}", path.display());
    }
    file.display().to_string()
}

fn kind_name(kind: SymbolKind) -> &'static str {
    match kind {
        SymbolKind::Class => "Class",
        SymbolKind::TypeParameter => "TypeParameter",
        SymbolKind::Enum => "Enum",
        SymbolKind::EnumMember => "EnumMember",
        SymbolKind::Typedef => "Typedef",
        SymbolKind::Function => "Function",
        SymbolKind::GlobalField => "GlobalField",
        SymbolKind::Field => "Field",
        SymbolKind::Method => "Method",
        SymbolKind::Constructor => "Constructor",
        SymbolKind::Destructor => "Destructor",
        SymbolKind::Parameter => "Parameter",
        SymbolKind::LocalVariable => "LocalVariable",
        SymbolKind::PreprocessorMacro => "PreprocessorMacro",
    }
}

fn timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|")
}

fn escape_inline(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace('\r', "\\r")
        .replace('\n', "\\n")
        .replace('\t', "\\t")
}
