use reforger_language_server::lexer::{lex, TokenKind};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/lexer-fixtures.report.md";

struct Fixture {
    path: &'static str,
    source: &'static str,
}

fn main() -> Result<(), String> {
    let out_path = output_path()?;
    let report = render_report();

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&out_path, report)
        .map_err(|error| format!("Failed to write report {}: {error}", out_path.display()))?;

    println!("Wrote lexer fixture report: {}", out_path.display());
    Ok(())
}

fn output_path() -> Result<PathBuf, String> {
    let mut args = env::args().skip(1);
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example lexer_report -- [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn fixtures() -> [Fixture; 4] {
    [
        Fixture {
            path: "fixtures/lexer/declarations.c",
            source: include_str!("../../fixtures/lexer/declarations.c"),
        },
        Fixture {
            path: "fixtures/lexer/game_data_player_commands_config.c",
            source: include_str!("../../fixtures/lexer/game_data_player_commands_config.c"),
        },
        Fixture {
            path: "fixtures/lexer/methods_generics.c",
            source: include_str!("../../fixtures/lexer/methods_generics.c"),
        },
        Fixture {
            path: "fixtures/lexer/trivia_preprocessor_rpc.c",
            source: include_str!("../../fixtures/lexer/trivia_preprocessor_rpc.c"),
        },
    ]
}

fn render_report() -> String {
    let mut report = String::new();
    report.push_str("# Lexer Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example lexer_report`.\n\n");
    report.push_str("This report shows lexer input vs output for committed fixtures. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures() {
        append_fixture_report(&mut report, fixture);
    }

    report
}

fn append_fixture_report(report: &mut String, fixture: Fixture) {
    let tokens = lex(fixture.source);
    let mut counts = BTreeMap::<String, usize>::new();
    let mut error_count = 0usize;

    for token in &tokens {
        let name = format!("{:?}", token.kind);
        *counts.entry(name).or_default() += 1;
        if matches!(
            token.kind,
            TokenKind::Unknown
                | TokenKind::UnterminatedString
                | TokenKind::UnterminatedBlockComment
        ) {
            error_count += 1;
        }
    }

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str("### Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!("| Lines | {} |\n", line_count(fixture.source)));
    report.push_str(&format!("| Tokens including trivia | {} |\n", tokens.len()));
    report.push_str(&format!("| Error tokens | {} |\n\n", error_count));

    report.push_str("### Token Counts\n\n");
    report.push_str("| Token kind | Count |\n");
    report.push_str("| --- | ---: |\n");
    for (kind, count) in counts {
        report.push_str(&format!("| `{}` | {} |\n", escape_table(&kind), count));
    }
    report.push('\n');

    report.push_str("### Token Stream\n\n");
    report.push_str("| # | Kind | Span | Line:Col | Text |\n");
    report.push_str("| ---: | --- | --- | --- | --- |\n");
    for (index, token) in tokens.iter().enumerate() {
        let text = if token.kind == TokenKind::Eof {
            String::new()
        } else {
            fixture.source[token.span.start..token.span.end].to_string()
        };
        let (line, column) = line_column(fixture.source, token.span.start);
        report.push_str(&format!(
            "| {} | `{}` | {}..{} | {}:{} | `{}` |\n",
            index,
            escape_table(&format!("{:?}", token.kind)),
            token.span.start,
            token.span.end,
            line,
            column,
            escape_code(&text)
        ));
    }
    report.push('\n');
}

fn line_count(source: &str) -> usize {
    source.lines().count()
}

fn line_column(source: &str, offset: usize) -> (usize, usize) {
    let mut line = 1usize;
    let mut column = 1usize;

    for (index, value) in source.char_indices() {
        if index >= offset {
            break;
        }

        if value == '\n' {
            line += 1;
            column = 1;
        } else {
            column += 1;
        }
    }

    (line, column)
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|")
}

fn escape_code(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace('\r', "\\r")
        .replace('\n', "\\n")
        .replace('\t', "\\t")
}
