use reforger_language_server::lsp::{parser_diagnostics_for_source, LspDiagnostic};
use reforger_language_server::parser::parse_source;
use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_FIXTURE_ROOT: &str = "tools/fixtures/diagnostics";
const DEFAULT_OUTPUT: &str = "tools/reports/lsp-diagnostics-corpus.report.md";

struct Args {
    fixtures: PathBuf,
    out: PathBuf,
}

struct FileRow {
    path: PathBuf,
    bytes: usize,
    parse_diagnostics: usize,
    lsp_diagnostics: Vec<LspDiagnostic>,
    zero_width_ranges: usize,
    invalid_ranges: usize,
    first_snippet: Option<String>,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let args = parse_args()?;
    if !args.fixtures.is_dir() {
        return Err(format!(
            "Diagnostics fixture folder does not exist: {}",
            args.fixtures.display()
        ));
    }

    let mut files = Vec::new();
    collect_script_files(&args.fixtures, &mut files)?;
    files.sort();

    let mut rows = Vec::new();
    let mut message_frequency = BTreeMap::<String, usize>::new();
    for file in files {
        let source = fs::read_to_string(&file)
            .map_err(|error| format!("Failed to read {}: {error}", file.display()))?;
        let parse = parse_source(&source);
        let diagnostics = parser_diagnostics_for_source(&source, &parse.diagnostics);
        for diagnostic in &diagnostics {
            *message_frequency
                .entry(diagnostic.message.clone())
                .or_default() += 1;
        }
        rows.push(FileRow {
            path: file,
            bytes: source.len(),
            parse_diagnostics: parse.diagnostics.len(),
            zero_width_ranges: diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.range.start == diagnostic.range.end)
                .count(),
            invalid_ranges: diagnostics
                .iter()
                .filter(|diagnostic| !range_is_inside_source(&source, diagnostic))
                .count(),
            first_snippet: diagnostics
                .first()
                .map(|diagnostic| snippet_for_range(&source, diagnostic)),
            lsp_diagnostics: diagnostics,
        });
    }

    let mut markdown = String::new();
    writeln!(markdown, "# LSP Diagnostics Corpus Report").unwrap();
    writeln!(markdown).unwrap();
    writeln!(
        markdown,
        "> Human-review output generated by `node tools/lsp-diagnostics-corpus-report.mjs`."
    )
    .unwrap();
    writeln!(markdown).unwrap();
    writeln!(markdown, "This report scans committed malformed parser fixtures and reviews the LSP diagnostic projection. Diagnostics are extension parser facts only; Workbench remains compiler truth.").unwrap();
    writeln!(markdown).unwrap();

    append_summary(&mut markdown, &args.fixtures, &rows);
    append_message_frequency(&mut markdown, &message_frequency);
    append_file_table(&mut markdown, &args.fixtures, &rows);
    append_zero_diagnostic_files(&mut markdown, &args.fixtures, &rows);
    append_range_quality_issues(&mut markdown, &args.fixtures, &rows);
    append_diagnostic_details(&mut markdown, &args.fixtures, &rows);

    if let Some(parent) = args.out.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Failed to create {}: {error}", parent.display()))?;
    }
    fs::write(&args.out, markdown)
        .map_err(|error| format!("Failed to write {}: {error}", args.out.display()))?;
    println!("Wrote {}", args.out.display());
    Ok(())
}

fn parse_args() -> Result<Args, String> {
    let mut fixtures = repo_path(DEFAULT_FIXTURE_ROOT);
    let mut out = repo_path(DEFAULT_OUTPUT);
    let mut args = env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--fixtures" => {
                let Some(value) = args.next() else {
                    return Err("--fixtures requires a path".to_string());
                };
                fixtures = resolve_path(value);
            }
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = resolve_path(value);
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example lsp_diagnostics_corpus_report -- [--fixtures <path>] [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }
    Ok(Args { fixtures, out })
}

fn append_summary(markdown: &mut String, root: &Path, rows: &[FileRow]) {
    let total_diagnostics = rows
        .iter()
        .map(|row| row.lsp_diagnostics.len())
        .sum::<usize>();
    let files_with_diagnostics = rows
        .iter()
        .filter(|row| !row.lsp_diagnostics.is_empty())
        .count();
    let zero_width_ranges = rows.iter().map(|row| row.zero_width_ranges).sum::<usize>();
    let invalid_ranges = rows.iter().map(|row| row.invalid_ranges).sum::<usize>();

    writeln!(markdown, "## Summary").unwrap();
    writeln!(markdown).unwrap();
    writeln!(markdown, "| Metric | Value |").unwrap();
    writeln!(markdown, "| --- | ---: |").unwrap();
    writeln!(markdown, "| Fixture root | `{}` |", root.display()).unwrap();
    writeln!(markdown, "| Files | {} |", rows.len()).unwrap();
    writeln!(
        markdown,
        "| Files with diagnostics | {files_with_diagnostics} |"
    )
    .unwrap();
    writeln!(markdown, "| LSP diagnostics | {total_diagnostics} |").unwrap();
    writeln!(markdown, "| Zero-width ranges | {zero_width_ranges} |").unwrap();
    writeln!(markdown, "| Invalid ranges | {invalid_ranges} |").unwrap();
    writeln!(markdown).unwrap();
}

fn append_message_frequency(markdown: &mut String, messages: &BTreeMap<String, usize>) {
    writeln!(markdown, "## Diagnostic Message Frequency").unwrap();
    writeln!(markdown).unwrap();
    if messages.is_empty() {
        writeln!(markdown, "None.").unwrap();
        writeln!(markdown).unwrap();
        return;
    }
    writeln!(markdown, "| Message | Count |").unwrap();
    writeln!(markdown, "| --- | ---: |").unwrap();
    for (message, count) in messages {
        writeln!(markdown, "| {} | {count} |", escape_cell(message)).unwrap();
    }
    writeln!(markdown).unwrap();
}

fn append_file_table(markdown: &mut String, root: &Path, rows: &[FileRow]) {
    writeln!(markdown, "## File Results").unwrap();
    writeln!(markdown).unwrap();
    writeln!(
        markdown,
        "| File | Bytes | Parse diagnostics | LSP diagnostics | Zero-width ranges | Invalid ranges |"
    )
    .unwrap();
    writeln!(markdown, "| --- | ---: | ---: | ---: | ---: | ---: |").unwrap();
    for row in rows {
        writeln!(
            markdown,
            "| `{}` | {} | {} | {} | {} | {} |",
            relative_path(root, &row.path),
            row.bytes,
            row.parse_diagnostics,
            row.lsp_diagnostics.len(),
            row.zero_width_ranges,
            row.invalid_ranges
        )
        .unwrap();
    }
    writeln!(markdown).unwrap();
}

fn append_zero_diagnostic_files(markdown: &mut String, root: &Path, rows: &[FileRow]) {
    let zero_rows = rows
        .iter()
        .filter(|row| row.lsp_diagnostics.is_empty())
        .collect::<Vec<_>>();
    writeln!(markdown, "## Zero-Diagnostic Malformed Fixtures").unwrap();
    writeln!(markdown).unwrap();
    if zero_rows.is_empty() {
        writeln!(markdown, "None.").unwrap();
        writeln!(markdown).unwrap();
        return;
    }
    writeln!(markdown, "| File | Bytes |").unwrap();
    writeln!(markdown, "| --- | ---: |").unwrap();
    for row in zero_rows {
        writeln!(
            markdown,
            "| `{}` | {} |",
            relative_path(root, &row.path),
            row.bytes
        )
        .unwrap();
    }
    writeln!(markdown).unwrap();
}

fn append_range_quality_issues(markdown: &mut String, root: &Path, rows: &[FileRow]) {
    let issue_rows = rows
        .iter()
        .filter(|row| row.zero_width_ranges > 0 || row.invalid_ranges > 0)
        .collect::<Vec<_>>();
    writeln!(markdown, "## Range Quality Issues").unwrap();
    writeln!(markdown).unwrap();
    if issue_rows.is_empty() {
        writeln!(markdown, "None.").unwrap();
        writeln!(markdown).unwrap();
        return;
    }
    writeln!(
        markdown,
        "| File | Zero-width ranges | Invalid ranges | First snippet |"
    )
    .unwrap();
    writeln!(markdown, "| --- | ---: | ---: | --- |").unwrap();
    for row in issue_rows {
        writeln!(
            markdown,
            "| `{}` | {} | {} | `{}` |",
            relative_path(root, &row.path),
            row.zero_width_ranges,
            row.invalid_ranges,
            escape_cell(row.first_snippet.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    writeln!(markdown).unwrap();
}

fn append_diagnostic_details(markdown: &mut String, root: &Path, rows: &[FileRow]) {
    writeln!(markdown, "## Diagnostic Details").unwrap();
    for row in rows {
        writeln!(markdown).unwrap();
        writeln!(markdown, "### `{}`", relative_path(root, &row.path)).unwrap();
        writeln!(markdown).unwrap();
        if row.lsp_diagnostics.is_empty() {
            writeln!(markdown, "No diagnostics.").unwrap();
            continue;
        }
        for (index, diagnostic) in row.lsp_diagnostics.iter().enumerate() {
            writeln!(
                markdown,
                "{}. `{}` `{}` severity {} at {}",
                index + 1,
                diagnostic.source,
                diagnostic.code,
                diagnostic.severity,
                format_diagnostic_range(diagnostic)
            )
            .unwrap();
            writeln!(markdown, "   Message: {}", escape_cell(&diagnostic.message)).unwrap();
            if index == 0 {
                if let Some(snippet) = &row.first_snippet {
                    writeln!(markdown).unwrap();
                    writeln!(markdown, "~~~enforce").unwrap();
                    writeln!(markdown, "{snippet}").unwrap();
                    writeln!(markdown, "~~~").unwrap();
                }
            }
        }
    }
    writeln!(markdown).unwrap();
}

fn collect_script_files(folder: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(folder)
        .map_err(|error| format!("Failed to read folder {}: {error}", folder.display()))?
    {
        let entry = entry
            .map_err(|error| format!("Failed to read entry in {}: {error}", folder.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_script_files(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "c") {
            files.push(path);
        }
    }
    Ok(())
}

fn range_is_inside_source(source: &str, diagnostic: &LspDiagnostic) -> bool {
    let lines = source.lines().collect::<Vec<_>>();
    if lines.is_empty() {
        return diagnostic.range.start.line == 0 && diagnostic.range.end.line == 0;
    }
    let start_line = diagnostic.range.start.line as usize;
    let end_line = diagnostic.range.end.line as usize;
    if start_line >= lines.len()
        || end_line >= lines.len()
        || diagnostic.range.start.line > diagnostic.range.end.line
    {
        return false;
    }
    let start_line_len = lines[start_line].encode_utf16().count() as u32;
    let end_line_len = lines[end_line].encode_utf16().count() as u32;
    diagnostic.range.start.character <= start_line_len
        && diagnostic.range.end.character <= end_line_len
        && (diagnostic.range.start.line < diagnostic.range.end.line
            || diagnostic.range.start.character <= diagnostic.range.end.character)
}

fn snippet_for_range(source: &str, diagnostic: &LspDiagnostic) -> String {
    let lines: Vec<&str> = source.lines().collect();
    if lines.is_empty() {
        return "<empty source>".to_string();
    }
    let target_line = diagnostic.range.start.line as usize;
    let start = target_line.saturating_sub(1);
    let end = (target_line + 2).min(lines.len());
    let mut snippet = String::new();
    for line_index in start..end {
        let marker = if line_index == target_line { ">" } else { " " };
        let line = lines[line_index].replace('\t', "\\t");
        writeln!(snippet, "{marker} {:>4} | {}", line_index + 1, line).unwrap();
        if line_index == target_line {
            let raw_start_col = diagnostic.range.start.character as usize;
            let raw_end_col = diagnostic.range.end.character as usize;
            let start_col = raw_start_col.min(160);
            let caret_count = raw_end_col.saturating_sub(raw_start_col).max(1).min(80);
            let truncated_marker = if raw_start_col > start_col {
                " ..."
            } else {
                ""
            };
            writeln!(
                snippet,
                "       | {}{}{}",
                " ".repeat(start_col),
                "^".repeat(caret_count),
                truncated_marker
            )
            .unwrap();
        }
    }
    snippet.trim_end().to_string()
}

fn format_diagnostic_range(diagnostic: &LspDiagnostic) -> String {
    format!(
        "{}:{}-{}:{}",
        diagnostic.range.start.line + 1,
        diagnostic.range.start.character + 1,
        diagnostic.range.end.line + 1,
        diagnostic.range.end.character + 1
    )
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

fn escape_cell(value: &str) -> String {
    value
        .replace('|', "\\|")
        .replace('\n', " ")
        .replace('`', "\\`")
}

fn resolve_path(value: String) -> PathBuf {
    let path = PathBuf::from(value);
    if path.is_absolute() {
        path
    } else {
        repo_path(path)
    }
}

fn repo_path(relative: impl AsRef<Path>) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .join(relative)
}
