use reforger_language_server::parser::parse_source;
use reforger_language_server::syntax::{SyntaxElement, SyntaxKind, SyntaxNode};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_REPORT_RELATIVE_PATH: &str = "tools/reports/parser-fixtures.report.md";

struct Fixture {
    path: &'static str,
    source: &'static str,
}

fn main() -> Result<(), String> {
    let out_path = output_path()?;
    let report = render_report();

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create report folder {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(&out_path, report)
        .map_err(|error| format!("Failed to write report {}: {error}", out_path.display()))?;

    println!("Wrote parser fixture report: {}", out_path.display());
    Ok(())
}

fn output_path() -> Result<PathBuf, String> {
    let mut args = env::args().skip(1);
    let mut out: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => {
                let Some(value) = args.next() else {
                    return Err("--out requires a path".to_string());
                };
                out = Some(PathBuf::from(value));
            }
            "--help" | "-h" => {
                println!("Usage: cargo run --manifest-path server/Cargo.toml --example parser_report -- [--out <path>]");
                std::process::exit(0);
            }
            _ => return Err(format!("Unknown argument: {arg}")),
        }
    }

    Ok(match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join(DEFAULT_REPORT_RELATIVE_PATH),
    })
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("server crate should be inside the repository root")
        .to_path_buf()
}

fn fixtures() -> [Fixture; 11] {
    [
        Fixture {
            path: "tools/fixtures/parser/core_types_declarations.c",
            source: include_str!("../../tools/fixtures/parser/core_types_declarations.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/attributes_rpc_workbench.c",
            source: include_str!("../../tools/fixtures/parser/attributes_rpc_workbench.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/modded_game_mode_members.c",
            source: include_str!("../../tools/fixtures/parser/modded_game_mode_members.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/preprocessor_directives.c",
            source: include_str!("../../tools/fixtures/parser/preprocessor_directives.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_network_component.c",
            source: include_str!("../../tools/fixtures/parser/game_building_network_component.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_building_provider_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_building_provider_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editable_group_excerpt.c",
            source: include_str!("../../tools/fixtures/parser/game_editable_group_excerpt.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_editor_preview_params.c",
            source: include_str!("../../tools/fixtures/parser/game_editor_preview_params.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c",
            source: include_str!(
                "../../tools/fixtures/parser/workbench_basic_code_formatter_excerpt.c"
            ),
        },
        Fixture {
            path: "tools/fixtures/parser/game_optional_semicolon_shapes.c",
            source: include_str!("../../tools/fixtures/parser/game_optional_semicolon_shapes.c"),
        },
        Fixture {
            path: "tools/fixtures/parser/game_field_initializer_call_shapes.c",
            source: include_str!(
                "../../tools/fixtures/parser/game_field_initializer_call_shapes.c"
            ),
        },
    ]
}

fn render_report() -> String {
    let mut report = String::new();
    report.push_str("# Parser Fixture Report\n\n");
    report.push_str("> Human-review output generated by `cargo run --manifest-path server/Cargo.toml --example parser_report`.\n\n");
    report.push_str("This report shows parser input vs structured output for committed fixtures. It is review data only; Workbench remains compiler truth.\n\n");

    for fixture in fixtures() {
        append_fixture_report(&mut report, fixture);
    }

    report
}

fn append_fixture_report(report: &mut String, fixture: Fixture) {
    let parse = parse_source(fixture.source);
    let mut counts = BTreeMap::<SyntaxKind, usize>::new();
    count_kinds(&parse.root, &mut counts);

    report.push_str(&format!("## `{}`\n\n", fixture.path));
    report.push_str("### Summary\n\n");
    report.push_str("| Metric | Value |\n");
    report.push_str("| --- | ---: |\n");
    report.push_str(&format!("| Bytes | {} |\n", fixture.source.len()));
    report.push_str(&format!("| Lines | {} |\n", fixture.source.lines().count()));
    report.push_str(&format!(
        "| Tokens preserved | {} |\n",
        parse.root.token_count()
    ));
    report.push_str(&format!(
        "| Diagnostics | {} |\n\n",
        parse.diagnostics.len()
    ));

    if !parse.diagnostics.is_empty() {
        report.push_str("### Diagnostics\n\n");
        report.push_str("| Message | Span |\n");
        report.push_str("| --- | --- |\n");
        for diagnostic in &parse.diagnostics {
            report.push_str(&format!(
                "| `{}` | {}..{} |\n",
                escape_table(&diagnostic.message),
                diagnostic.span.start,
                diagnostic.span.end
            ));
        }
        report.push('\n');
    }

    report.push_str("### Syntax Kind Counts\n\n");
    report.push_str("| Syntax kind | Count |\n");
    report.push_str("| --- | ---: |\n");
    for (kind, count) in counts {
        report.push_str(&format!("| `{:?}` | {} |\n", kind, count));
    }
    report.push('\n');

    report.push_str("### Tree Outline\n\n");
    append_outline(report, &parse.root, 0);
    report.push('\n');
}

fn count_kinds(node: &SyntaxNode, counts: &mut BTreeMap<SyntaxKind, usize>) {
    *counts.entry(node.kind).or_default() += 1;
    for child in &node.children {
        if let SyntaxElement::Node(child_node) = child {
            count_kinds(child_node, counts);
        }
    }
}

fn append_outline(report: &mut String, node: &SyntaxNode, depth: usize) {
    report.push_str(&format!(
        "{}- `{:?}` {}..{}\n",
        "  ".repeat(depth),
        node.kind,
        node.span.start,
        node.span.end
    ));

    for child in &node.children {
        if let SyntaxElement::Node(child_node) = child {
            append_outline(report, child_node, depth + 1);
        }
    }
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|")
}
